# Generated by Django 3.2.5 on 2022-06-28 13:06

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_squashed_initial'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AlterField(
            model_name='customoncallshift',
            name='frequency',
            field=models.IntegerField(choices=[(3, 'Hourly'), (0, 'Daily'), (1, 'Weekly'), (2, 'Monthly')], default=None, null=True),
        ),
    ]
