# Generated by Django 3.2.5 on 2022-06-28 13:07

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_customoncallshift_frequency'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name='customoncallshift',
            name='until',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
