# Generated by Django 3.2.13 on 2022-07-12 08:03

from django.db import migrations, models


def fill_rotation_start_field(apps, schema_editor):
    CustomOnCallShift = apps.get_model("schedules", "CustomOnCallShift")
    shifts = CustomOnCallShift.objects.all()
    shifts_to_update = []
    for shift in shifts:
        shift.rotation_start = shift.start
        shifts_to_update.append(shift)

    CustomOnCallShift.objects.bulk_update(shifts_to_update, ["rotation_start"], batch_size=5000)


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20220704_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='customoncallshift',
            name='rotation_start',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.RunPython(fill_rotation_start_field, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customoncallshift',
            name='rotation_start',
            field=models.DateTimeField(),
        ),
    ]
