# Generated by Django 3.2.13 on 2022-07-22 11:54

from django.db import migrations, models
import django.db.models.deletion
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_customoncallshift_rotation_start'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name='customoncallshift',
            name='updated_shift',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_shift', to='schedules.customoncallshift'),
        ),
        migrations.AddField(
            model_name='customoncallshift',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
