# Generated by Django 3.2.13 on 2022-09-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_customoncallshift_updated_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='customoncallshift',
            name='sequence_number',
            field=models.IntegerField(default=0),
        ),
    ]
