# Generated by Django 3.2.18 on 2023-03-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20221201_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallschedulecalendar',
            name='enable_web_overrides',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
