# Generated by Django 3.2.18 on 2023-05-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_oncallschedule_cached_ical_final_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncallschedule',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterUniqueTogether(
            name='oncallschedule',
            unique_together=set(),
        ),
    ]
