# Generated by Django 4.2.16 on 2024-10-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_slackteamidentity__unified_slack_app_installed'),
        ('schedules', '0017_alter_oncallschedule_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallschedule',
            name='slack_channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slack.slackchannel'),
        ),
    ]
