# Generated by Django 4.2.16 on 2024-10-21 17:35
import logging

from django.db import migrations
import django_migration_linter as linter

logger = logging.getLogger(__name__)

def populate_slack_channel(apps, schema_editor):
    OnCallSchedule = apps.get_model("schedules", "OnCallSchedule")
    SlackChannel = apps.get_model("slack", "SlackChannel")
    Organization = apps.get_model("user_management", "Organization")

    logger.info("Starting migration to populate slack_channel field.")

    sql = f"""
    UPDATE {OnCallSchedule._meta.db_table} AS ocs
    JOIN {Organization._meta.db_table} AS org ON org.id = ocs.organization_id
    JOIN {SlackChannel._meta.db_table} AS sc ON sc.slack_id = ocs.channel
                         AND sc.slack_team_identity_id = org.slack_team_identity_id
    SET ocs.slack_channel_id = sc.id
    WHERE ocs.channel IS NOT NULL
      AND org.slack_team_identity_id IS NOT NULL;
    """

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql)
        updated_rows = cursor.rowcount  # Number of rows updated

    logger.info(f"Bulk updated {updated_rows} OnCallSchedules with their Slack channel.")
    logger.info("Finished migration to populate slack_channel field.")

class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0018_oncallschedule_slack_channel'),
    ]

    operations = [
        # simply setting this new field is okay, we are not deleting the value of channel
        # therefore, no need to revert it
        linter.IgnoreMigration(),
        migrations.RunPython(populate_slack_channel, migrations.RunPython.noop),
    ]
