# Generated by Django 4.2.16 on 2024-11-06 21:13

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0019_auto_20241021_1735'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name='oncallschedule',
            name='channel',
        ),
    ]
