# Generated by Django 4.2.16 on 2024-11-20 20:12

import common.migrations.remove_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0019_auto_20241021_1735'),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldState(
            model_name='oncallschedule',
            name='channel',
        ),
    ]
