# Generated by Django 4.2.16 on 2024-11-20 20:12

import common.migrations.remove_field
import django_migration_linter as linter
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0020_remove_oncallschedule_channel_state'),
    ]

    operations = [
        linter.IgnoreMigration(),
        common.migrations.remove_field.RemoveFieldDB(
            model_name='oncallschedule',
            name='channel',
            remove_state_migration=('schedules', '0020_remove_oncallschedule_channel_state'),
        ),
    ]
