{{- if .Values.detached_integrations.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oncall.detached_integrations.fullname" . }}
  labels:
    {{- include "oncall.detached_integrations.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oncall.detached_integrations.selectorLabels" . | nindent 4 }}
{{- end -}}
