{{- if .Values.detached_integrations_service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oncall.detached_integrations.fullname" . }}-external
  labels:
    {{- include "oncall.detached_integrations.labels" . | nindent 4 }}
  {{- with .Values.detached_integrations_service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.detached_integrations_service.type }}
  ports:
    - port: {{ .Values.detached_integrations_service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.detached_integrations_service.type "NodePort") (.Values.detached_integrations_service.nodePort) }}
      nodePort: {{ .Values.detached_integrations_service.nodePort }}
      {{- end }}
  selector:
    {{- include "oncall.detached_integrations.selectorLabels" . | nindent 4 }}
{{- end }}
