# Generated by Django 3.2.16 on 2022-12-29 14:42

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_squashed_initial'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AlterField(
            model_name='telegrammessage',
            name='message_type',
            field=models.IntegerField(choices=[(0, 'Alert group message'), (1, 'Actions message'), (2, 'Log message'), (3, 'Alert can not be rendered'), (4, 'Alert group message with action buttons and alert group log'), (5, 'Link to channel message'), (6, 'Link to channel message without title')]),
        ),
    ]
