# Generated by Django 4.2.15 on 2024-09-10 03:01

import apps.mattermost.models.channel
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0022_alter_team_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MattermostChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_primary_key', models.CharField(default=apps.mattermost.models.channel.generate_public_primary_key_for_mattermost_channel, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('mattermost_team_id', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(default=None, max_length=100)),
                ('display_name', models.CharField(default=None, max_length=100)),
                ('is_default_channel', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mattermost_channels', to='user_management.organization')),
            ],
            options={
                'unique_together': {('organization', 'channel_id')},
            },
        ),
    ]
