version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/grafana-plugin"
    schedule:
      interval: "monthly"
    labels:
      - "pr:dependencies"
      - "pr:no changelog"
      - "pr:no public docs"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "pr:dependencies"
      - "pr:no changelog"
      - "pr:no public docs"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "pr:dependencies"
      - "pr:no changelog"
      - "pr:no public docs"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "pr:dependencies"
      - "pr:no changelog"
      - "pr:no public docs"
