base_url: 172.17.0.1:30001
base_url_protocol: http

env:
  - name: GRAFANA_CLOUD_NOTIFICATIONS_ENABLED
    value: "False"
image:
  tag: latest
  pullPolicy: Always
broker:
  type: redis
redis:
  architecture: standalone # don't run replicas, just eats up resources
rabbitmq:
  enabled: false
oncall:
  devMode: true
engine:
  replicaCount: 1
celery:
  replicaCount: 1
  worker_beat_enabled: false

grafana:
  replicas: 1
  env:
    GF_FEATURE_TOGGLES_ENABLE: topnav
    GF_SECURITY_ADMIN_PASSWORD: oncall
    GF_SECURITY_ADMIN_USER: oncall
    GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-oncall-app
    GF_DATABASE_SSL_MODE: disable
  # by settings grafana.plugins to [] and configuring grafana.extraVolumeMounts we are using the locally built
  # OnCall plugin rather than the latest published version
  plugins: []
  extraVolumeMounts:
    - name: plugins
      mountPath: /var/lib/grafana/plugins/grafana-plugin
      # hostPath is defined in .github/kind.yml
      hostPath: /oncall-plugin
      readOnly: true
  service:
    type: NodePort
    nodePort: 30002

mariadb:
  enabled: false
database:
  type: sqlite
ingress:
  enabled: false
ingress-nginx:
  enabled: false
cert-manager:
  enabled: false
service:
  enabled: true
  type: NodePort
  port: 8080
  nodePort: 30001
