import { operations } from 'network/oncall-api/autogenerated-api.types';

export enum MaintenanceMode {
  Debug = 0,
  Maintenance = 1,
}

export type AlertReceiveChannelCounters =
  operations['alert_receive_channels_counters_retrieve']['responses']['200']['content']['application/json'][string];

export interface ContactPoint {
  dataSourceName: string;
  dataSourceId: string;
  contactPoint: string;
  notificationConnected: boolean;
}

export interface ServiceNowStatus {
  id: number;
  name: string;
}
