import { omit } from 'lodash-es';
import { action, observable, runInAction, makeAutoObservable } from 'mobx';

import { AlertTemplatesDTO } from 'models/alert_templates/alert_templates';
import { Alert } from 'models/alertgroup/alertgroup.types';
import { ChannelFilter } from 'models/channel_filter/channel_filter.types';
import { GrafanaTeam } from 'models/grafana_team/grafana_team.types';
import { Heartbeat } from 'models/heartbeat/heartbeat.types';
import { OutgoingWebhook } from 'models/outgoing_webhook/outgoing_webhook.types';
import { makeRequest } from 'network';
import { ApiSchemas } from 'network/oncall-api/api.types';
import { operations } from 'network/oncall-api/autogenerated-api.types';
import onCallApi from 'network/oncall-api/http-client';
import { move } from 'state/helpers';
import { RootBaseStore } from 'state/rootBaseStore';
import { SelectOption } from 'state/types';
import { showApiError } from 'utils';
import { WithGlobalNotification } from 'utils/decorators';

import { AlertReceiveChannelCounters, ContactPoint, MaintenanceMode } from './alert_receive_channel.types';

export class AlertReceiveChannelStore {
  path = '/alert_receive_channels/';

  rootStore: RootBaseStore;

  @observable.shallow
  searchResult: Array<ApiSchemas['AlertReceiveChannel']['id']>;

  @observable.shallow
  paginatedSearchResult: {
    count?: number;
    results?: Array<ApiSchemas['AlertReceiveChannel']['id']>;
    page_size?: number;
  } = {};

  @observable.shallow
  items: { [id: string]: ApiSchemas['AlertReceiveChannel'] } = {};

  @observable.shallow
  counters: { [id: string]: AlertReceiveChannelCounters } = {};

  @observable
  channelFilterIds: { [id: string]: Array<ChannelFilter['id']> } = {};

  @observable.shallow
  channelFilters: { [id: string]: ChannelFilter } = {};

  @observable
  alertReceiveChannelToHeartbeat: {
    [id: string]: Heartbeat['id'];
  } = {};

  @observable.shallow
  actions: { [id: string]: OutgoingWebhook[] } = {};

  @observable.shallow
  alertReceiveChannelOptions: Array<ApiSchemas['AlertReceiveChannelIntegrationOptions']> = [];

  @observable.shallow
  templates: { [id: string]: AlertTemplatesDTO[] } = {};

  @observable
  connectedContactPoints: { [id: string]: ContactPoint[] } = {};

  constructor(rootStore: RootBaseStore) {
    makeAutoObservable(this, undefined, { autoBind: true });
    this.rootStore = rootStore;
  }

  getSearchResult(_query = '') {
    if (!this.searchResult) {
      return undefined;
    }

    return this.searchResult.map(
      (alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id']) => this.items?.[alertReceiveChannelId]
    );
  }

  getPaginatedSearchResult(_query = '') {
    if (!this.paginatedSearchResult) {
      return undefined;
    }

    return {
      page_size: this.paginatedSearchResult.page_size,
      count: this.paginatedSearchResult.count,
      results: this.paginatedSearchResult.results?.map(
        (alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id']) => this.items?.[alertReceiveChannelId]
      ),
    };
  }

  @action
  async getById(
    id: ApiSchemas['AlertReceiveChannel']['id'],
    skipErrorHandling = false // TODO: check it
  ): Promise<ApiSchemas['AlertReceiveChannel']> {
    const alertReceiveChannel = await onCallApi.GET('/alert_receive_channels/{id}/', { params: { path: { id } } });

    runInAction(() => {
      // @ts-ignore
      this.items = {
        ...this.items,
        [id]: omit(alertReceiveChannel.data, 'heartbeat'),
      };
    });

    this.populateHearbeats([alertReceiveChannel.data]);

    return alertReceiveChannel.data;
  }

  @action
  async updateItems(query: any = '') {
    const params = typeof query === 'string' ? { search: query } : query;

    const { results } = await makeRequest(this.path, { params });

    runInAction(() => {
      this.items = {
        ...this.items,
        ...results.reduce(
          (acc: { [key: number]: ApiSchemas['AlertReceiveChannel'] }, item: ApiSchemas['AlertReceiveChannel']) => ({
            ...acc,
            [item.id]: omit(item, 'heartbeat'),
          }),
          {}
        ),
      };
    });

    this.populateHearbeats(results);

    runInAction(() => {
      this.searchResult = results.map((item: ApiSchemas['AlertReceiveChannel']) => item.id);
    });

    this.updateCounters();

    return results;
  }

  async updatePaginatedItems({
    filters,
    page = 1,
    updateCounters = false,
    invalidateFn = undefined,
  }: {
    filters: operations['alert_receive_channels_list']['parameters']['query'];
    page: number;
    updateCounters: boolean;
    invalidateFn: () => boolean;
  }) {
    const { count, results, page_size } = await makeRequest(this.path, { params: { ...filters, page } });

    if (invalidateFn?.()) {
      return undefined;
    }

    runInAction(() => {
      this.items = {
        ...this.items,
        ...results.reduce(
          (acc: { [key: number]: ApiSchemas['AlertReceiveChannel'] }, item: ApiSchemas['AlertReceiveChannel']) => ({
            ...acc,
            [item.id]: omit(item, 'heartbeat'),
          }),
          {}
        ),
      };
    });

    this.populateHearbeats(results);

    runInAction(() => {
      this.paginatedSearchResult = {
        count,
        results: results.map((item: ApiSchemas['AlertReceiveChannel']) => item.id),
        page_size,
      };
    });

    if (updateCounters) {
      this.updateCounters();
    }

    return results;
  }

  populateHearbeats(alertReceiveChannels: Array<ApiSchemas['AlertReceiveChannel']>) {
    const heartbeats = alertReceiveChannels.reduce(
      (acc: any, alertReceiveChannel: ApiSchemas['AlertReceiveChannel']) => {
        if (alertReceiveChannel.heartbeat) {
          acc[alertReceiveChannel.heartbeat.id] = alertReceiveChannel.heartbeat;
        }

        return acc;
      },
      {}
    );

    runInAction(() => {
      this.rootStore.heartbeatStore.items = {
        ...this.rootStore.heartbeatStore.items,
        ...heartbeats,
      };
    });

    const alertReceiveChannelToHeartbeat = alertReceiveChannels.reduce(
      (acc: any, alertReceiveChannel: ApiSchemas['AlertReceiveChannel']) => {
        if (alertReceiveChannel.heartbeat) {
          acc[alertReceiveChannel.id] = alertReceiveChannel.heartbeat.id;
        }

        return acc;
      },
      {}
    );

    runInAction(() => {
      this.alertReceiveChannelToHeartbeat = {
        ...this.alertReceiveChannelToHeartbeat,
        ...alertReceiveChannelToHeartbeat,
      };
    });
  }

  @action
  async updateChannelFilters(alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id'], isOverwrite = false) {
    const response = await makeRequest(`/channel_filters/`, {
      params: { alert_receive_channel: alertReceiveChannelId },
    });

    const channelFilters = response.reduce(
      (acc: any, channelFilter: ChannelFilter) => ({
        ...acc,
        [channelFilter.id]: channelFilter,
      }),
      {}
    );

    runInAction(() => {
      this.channelFilters = {
        ...this.channelFilters,
        ...channelFilters,
      };
    });

    if (isOverwrite) {
      runInAction(() => {
        // This is needed because on Move Up/Down/Removal the store no longer reflects the correct state
        this.channelFilters = {
          ...channelFilters,
        };
      });
    }

    runInAction(() => {
      this.channelFilterIds = {
        ...this.channelFilterIds,
        [alertReceiveChannelId]: response.map((channelFilter: ChannelFilter) => channelFilter.id),
      };
    });
  }

  @action
  async updateChannelFilter(channelFilterId: ChannelFilter['id']) {
    const response = await makeRequest(`/channel_filters/${channelFilterId}/`, {});

    runInAction(() => {
      this.channelFilters = {
        ...this.channelFilters,
        [channelFilterId]: response,
      };
    });
  }

  async migrateChannel(id: ApiSchemas['AlertReceiveChannel']['id']) {
    return await makeRequest(`/alert_receive_channels/${id}/migrate`, {
      method: 'POST',
    });
  }

  async createChannelFilter(data: Partial<ChannelFilter>) {
    return await makeRequest('/channel_filters/', {
      method: 'POST',
      data,
    });
  }

  @action
  async saveChannelFilter(channelFilterId: ChannelFilter['id'], data: Partial<ChannelFilter>) {
    const response = await makeRequest(`/channel_filters/${channelFilterId}/`, {
      method: 'PUT',
      data,
    });

    runInAction(() => {
      this.channelFilters = {
        ...this.channelFilters,
        [response.id]: response,
      };
    });

    return response;
  }

  @action
  async moveChannelFilterToPosition(
    alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id'],
    oldIndex: number,
    newIndex: number
  ) {
    const channelFilterId = this.channelFilterIds[alertReceiveChannelId][oldIndex];

    this.channelFilterIds[alertReceiveChannelId] = move(
      this.channelFilterIds[alertReceiveChannelId],
      oldIndex,
      newIndex
    );

    await makeRequest(`/channel_filters/${channelFilterId}/move_to_position/?position=${newIndex}`, { method: 'PUT' });

    this.updateChannelFilters(alertReceiveChannelId, true);
  }

  @action
  async deleteChannelFilter(channelFilterId: ChannelFilter['id']) {
    const channelFilter = this.channelFilters[channelFilterId];

    this.channelFilterIds[channelFilter.alert_receive_channel].splice(
      this.channelFilterIds[channelFilter.alert_receive_channel].indexOf(channelFilterId),
      1
    );

    await makeRequest(`/channel_filters/${channelFilterId}`, {
      method: 'DELETE',
    });

    return this.updateChannelFilters(channelFilter.alert_receive_channel, true);
  }

  @action.bound
  async updateAlertReceiveChannelOptions() {
    const response = await makeRequest(`/alert_receive_channels/integration_options/`, {});

    runInAction(() => {
      this.alertReceiveChannelOptions = response;
    });
  }

  getIntegration(alertReceiveChannel: Partial<ApiSchemas['AlertReceiveChannel']>): SelectOption {
    return (
      this.alertReceiveChannelOptions &&
      alertReceiveChannel &&
      this.alertReceiveChannelOptions.find(
        (alertReceiveChannelOption: SelectOption) => alertReceiveChannelOption.value === alertReceiveChannel.integration
      )
    );
  }

  @action.bound
  @WithGlobalNotification({ success: 'Integration has been saved', failure: 'Failed to save integration' })
  async saveAlertReceiveChannel(
    id: ApiSchemas['AlertReceiveChannel']['id'],
    payload: Partial<ApiSchemas['AlertReceiveChannelUpdate']>
  ) {
    const { data } = await onCallApi.PUT('/alert_receive_channels/{id}/', {
      params: { path: { id } },
      body: { ...this.items[id], ...payload },
    });

    runInAction(() => {
      this.items = {
        ...this.items,
        [id]: data,
      };
    });
  }

  // TODO: handle skipErrorHandling
  @action.bound
  async create({ data, skipErrorHandling }: { data: ApiSchemas['AlertReceiveChannel']; skipErrorHandling?: boolean }) {
    const result = await onCallApi.POST('/alert_receive_channels/', { params: {}, body: data });
    await this.rootStore.organizationStore.loadCurrentOrganization();
    return result.data;
  }

  // TODO: handle skipErrorHandling
  @action.bound
  async update({
    id,
    data,
    skipErrorHandling,
  }: {
    id: ApiSchemas['AlertReceiveChannelUpdate']['id'];
    data: ApiSchemas['AlertReceiveChannelUpdate'];
    skipErrorHandling?: boolean;
  }) {
    const result = await onCallApi.PUT('/alert_receive_channels/{id}/', { params: { path: { id } }, body: data });
    await this.rootStore.organizationStore.loadCurrentOrganization();
    return result.data;
  }

  async deleteAlertReceiveChannel(id: ApiSchemas['AlertReceiveChannel']['id']) {
    return (await onCallApi.DELETE('/alert_receive_channels/{id}/', { params: { path: { id } } })).data;
  }

  @action
  async updateTemplates(alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id'], alertGroupId?: Alert['pk']) {
    const response = await makeRequest(`/alert_receive_channel_templates/${alertReceiveChannelId}/`, {
      params: { alert_group_id: alertGroupId },
      withCredentials: true,
    });

    runInAction(() => {
      this.templates = {
        ...this.templates,
        [alertReceiveChannelId]: response,
      };
    });
  }

  @action
  async refetchItemById(id: ApiSchemas['AlertReceiveChannel']['id']) {
    const item = await this.getById(id);

    runInAction(() => {
      this.items = {
        ...this.items,
        [id]: item,
      };
    });
  }

  @action
  async saveTemplates(
    alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id'],
    data: Partial<AlertTemplatesDTO>
  ) {
    const response = await makeRequest(`/alert_receive_channel_templates/${alertReceiveChannelId}/`, {
      method: 'PUT',
      data,
      withCredentials: true,
    });

    runInAction(() => {
      this.templates = {
        ...this.templates,
        [alertReceiveChannelId]: response,
      };
    });
  }

  async getGrafanaAlertingContactPoints() {
    return await makeRequest(`${this.path}contact_points/`, {}).catch(showApiError);
  }

  @action
  async updateConnectedContactPoints(alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id']) {
    const response = await makeRequest(`${this.path}${alertReceiveChannelId}/connected_contact_points `, {});

    runInAction(() => {
      this.connectedContactPoints = {
        ...this.connectedContactPoints,

        [alertReceiveChannelId]: response.reduce((list: ContactPoint[], payload) => {
          payload.contact_points.forEach((contactPoint: { name: string; notification_connected: boolean }) => {
            list.push({
              dataSourceName: payload.name,
              dataSourceId: payload.uid,
              contactPoint: contactPoint.name,
              notificationConnected: contactPoint.notification_connected,
            });
          });

          return list;
        }, []),
      };
    });
  }

  async connectContactPoint(
    alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id'],
    datasource_uid: string,
    contact_point_name: string
  ) {
    return await makeRequest(`${this.path}${alertReceiveChannelId}/connect_contact_point`, {
      method: 'POST',
      data: {
        datasource_uid,
        contact_point_name,
      },
    });
  }

  async disconnectContactPoint(
    alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id'],
    datasource_uid: string,
    contact_point_name: string
  ) {
    return await makeRequest(`${this.path}${alertReceiveChannelId}/disconnect_contact_point`, {
      method: 'POST',
      data: {
        datasource_uid,
        contact_point_name,
      },
    });
  }

  async createContactPoint(
    alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id'],
    datasource_uid: string,
    contact_point_name: string
  ) {
    return await makeRequest(`${this.path}${alertReceiveChannelId}/create_contact_point`, {
      method: 'POST',
      data: {
        datasource_uid,
        contact_point_name,
      },
    });
  }

  async getAccessLogs(alertReceiveChannelId: ApiSchemas['AlertReceiveChannel']['id']) {
    const { integration_log } = await makeRequest(`/alert_receive_channel_access_log/${alertReceiveChannelId}/`, {});

    return integration_log;
  }

  async sendDemoAlert(id: ApiSchemas['AlertReceiveChannel']['id'], payload: string = undefined) {
    const requestConfig: any = {
      method: 'POST',
    };

    if (payload) {
      requestConfig.data = {
        demo_alert_payload: payload,
      };
    }

    await makeRequest(`${this.path}${id}/send_demo_alert/`, requestConfig).catch(showApiError);
  }

  async sendDemoAlertToParticularRoute(id: ChannelFilter['id']) {
    await makeRequest(`/channel_filters/${id}/send_demo_alert/`, { method: 'POST' }).catch(showApiError);
  }

  async convertRegexpTemplateToJinja2Template(id: ChannelFilter['id']) {
    const result = await makeRequest(`/channel_filters/${id}/convert_from_regex_to_jinja2/`, { method: 'POST' }).catch(
      showApiError
    );
    return result;
  }

  async renderPreview(
    id: ApiSchemas['AlertReceiveChannel']['id'],
    template_name: string,
    template_body: string,
    payload: JSON
  ) {
    return await makeRequest(`${this.path}${id}/preview_template/`, {
      method: 'POST',
      data: { template_name, template_body, payload },
    });
  }

  async changeTeam(id: ApiSchemas['AlertReceiveChannel']['id'], teamId: GrafanaTeam['id']) {
    return await makeRequest(`${this.path}${id}/change_team`, {
      params: { team_id: String(teamId) },
      method: 'PUT',
    });
  }

  @action
  async updateCounters() {
    const counters = await makeRequest(`${this.path}counters`, {
      method: 'GET',
    });

    runInAction(() => {
      this.counters = counters;
    });
  }

  @action
  async updateCountersForIntegration(id: ApiSchemas['AlertReceiveChannel']['id']): Promise<any> {
    const counters = await makeRequest(`${this.path}${id}/counters`, {
      method: 'GET',
    });

    runInAction(() => {
      this.counters = {
        ...this.counters,
        [id]: {
          ...counters[id],
        },
      };
    });

    return counters;
  }

  startMaintenanceMode = (
    id: ApiSchemas['AlertReceiveChannel']['id'],
    mode: MaintenanceMode,
    duration: number
  ): Promise<void> =>
    makeRequest<null>(`${this.path}${id}/start_maintenance/`, {
      method: 'POST',
      data: {
        mode,
        duration,
      },
    });

  stopMaintenanceMode = (id: ApiSchemas['AlertReceiveChannel']['id']) =>
    makeRequest<null>(`${this.path}${id}/stop_maintenance/`, {
      method: 'POST',
    });

  addLabel = (id: ApiSchemas['AlertReceiveChannel']['id'], data) => {
    makeRequest(`${this.path}${id}/associate_label`, {
      method: 'POST',
      data,
    });
  };
}
