# Generated by Django 3.2.20 on 2023-07-14 11:36

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0001_squashed_initial'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.DeleteModel(
            name='HeartBeat',
        ),
    ]
