# Generated by Django 4.2.16 on 2024-11-20 15:39

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0002_delete_heartbeat'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name='integrationheartbeat',
            name='actual_check_up_task_id',
        ),
        migrations.RemoveField(
            model_name='integrationheartbeat',
            name='last_checkup_task_time',
        ),
    ]
