apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-25T10:28:21Z"
  name: grafana-oncall-app-provisioning
  namespace: default
data:
  grafana-oncall-app-provisioning.yaml: |
    apiVersion: 1
    plugins:
      - type: grafana-oncall-app
        disabled: false
