name: Linting and Tests - Pre-commit

on:
  workflow_call:
    inputs:
      python-dependency-paths:
        required: false
        type: string
        default: "engine/requirements.txt engine/requirements-dev.txt"

jobs:
  lint-entire-project:
    name: "Lint entire project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-python-deps
      # following 2 steps - need to install the frontend dependencies for the eslint/prettier/stylelint steps
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: "yarn"
          cache-dependency-path: grafana-plugin/yarn.lock
      - name: Use cached frontend dependencies
        id: cache-frontend-dependencies
        uses: actions/cache@v3
        with:
          path: grafana-plugin/node_modules
          key: ${{ runner.os }}-frontend-node-modules-${{ hashFiles('grafana-plugin/yarn.lock') }}
      - name: Install frontend dependencies
        if: steps.cache-frontend-dependencies.outputs.cache-hit != 'true'
        working-directory: grafana-plugin
        run: yarn install --frozen-lockfile --prefer-offline --network-timeout 500000
      - uses: pre-commit/action@v3.0.0
