# Generated by Django 3.2.5 on 2022-08-23 12:03

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_squashed_initial'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.DeleteModel(
            name='OrganizationLogRecord',
        ),
    ]
