# Generated by Django 4.2.7 on 2024-01-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_drop_unused_dynamic_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationpolicylogrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
