# Generated by Django 4.2.7 on 2023-12-21 02:59

from django.db import migrations, models

def update_category_field_for_important_notification(apps, schema_editor):
    UserNotificationPolicy = apps.get_model("base", "UserNotificationPolicy")

    UserNotificationPolicy.objects.filter(important=False, category=None).update(category=0)
    UserNotificationPolicy.objects.filter(important=True, category=None).update(category=1)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_drop_unused_dynamic_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpolicy',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Important')], default=None, null=True),
        ),
        migrations.RunPython(update_category_field_for_important_notification, migrations.RunPython.noop),
    ]
