# Generated by Django 3.2.16 on 2022-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='trigger_type',
            field=models.IntegerField(choices=[(0, 'As escalation step'), (1, 'As user notification step'), (2, 'Alert group new'), (3, 'Alert group acknowledge'), (4, 'Alert group resolve'), (5, 'Alert group silence'), (6, 'Alert group unsilence'), (7, 'Alert group unresolve'), (8, 'Schedule shift changed')], default=None, null=True),
        ),
    ]
