# Generated by Django 3.2.18 on 2023-04-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20230320_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='integration_filter',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='is_webhook_enabled',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='trigger_type',
            field=models.IntegerField(choices=[(0, 'Escalation step'), (1, 'Firing'), (2, 'Acknowledged'), (3, 'Resolved'), (4, 'Silenced'), (5, 'Unsilenced'), (6, 'Unresolved')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='webhookresponse',
            name='trigger_type',
            field=models.IntegerField(choices=[(0, 'Escalation step'), (1, 'Firing'), (2, 'Acknowledged'), (3, 'Resolved'), (4, 'Silenced'), (5, 'Unsilenced'), (6, 'Unresolved')]),
        ),
    ]
