# Generated by Django 3.2.16 on 2022-12-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_alter_webhook_trigger_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhooklog',
            old_name='request',
            new_name='data',
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='headers',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='trigger_type',
            field=models.IntegerField(choices=[(0, 'Escalation step'), (1, 'User notification'), (2, 'Triggered'), (3, 'Acknowledged'), (4, 'Resolved'), (5, 'Silenced'), (6, 'Unsilenced'), (7, 'Unresolved'), (8, 'Schedule shift change')], default=None, null=True),
        ),
    ]
