# Generated by Django 3.2.18 on 2023-04-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20230320_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='integration_filter',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='is_webhook_enabled',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
