# Generated by Django 3.2.18 on 2023-04-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_auto_20230418_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='is_legacy',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
