# Generated by Django 3.2.18 on 2023-04-26 16:31

from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_webhook_is_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='password',
            field=mirage.fields.EncryptedCharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='trigger_type',
            field=models.IntegerField(choices=[(0, 'Escalation step'), (1, 'Alert Group Created'), (2, 'Acknowledged'), (3, 'Resolved'), (4, 'Silenced'), (5, 'Unsilenced'), (6, 'Unresolved'), (7, 'Unacknowledged')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='webhookresponse',
            name='trigger_type',
            field=models.IntegerField(choices=[(0, 'Escalation step'), (1, 'Alert Group Created'), (2, 'Acknowledged'), (3, 'Resolved'), (4, 'Silenced'), (5, 'Unsilenced'), (6, 'Unresolved'), (7, 'Unacknowledged')]),
        ),
    ]
