# Generated by Django 3.2.19 on 2023-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_auto_20230426_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookresponse',
            name='event_data',
            field=models.TextField(default=None, null=True),
        ),
    ]
