# Generated by Django 3.2.19 on 2023-07-12 16:13

from django.db import migrations

from apps.alerts.models import CustomButton, EscalationPolicy
from apps.webhooks.models import Webhook


def migrate_custom_button_to_webhook(apps, schema_editor):

    for cb in CustomButton.objects.all():
        webhook, _ = Webhook.objects.get_or_create(
            organization=cb.organization,
            team=cb.team,
            name=cb.name,
            is_legacy=True,
            defaults=dict(
                created_at=cb.created_at,
                url=cb.webhook,
                username=cb.user,
                password=cb.password,
                authorization_header=cb.authorization_header,
                trigger_type=Webhook.TRIGGER_ESCALATION_STEP,
                forward_all=cb.forward_whole_payload,
                data=cb.data,
            )
        )
        # migrate related escalation policies
        policies = EscalationPolicy.objects.filter(
            step=EscalationPolicy.STEP_TRIGGER_CUSTOM_BUTTON,
            custom_button_trigger=cb,
        ).update(
            step=EscalationPolicy.STEP_TRIGGER_CUSTOM_WEBHOOK,
            custom_webhook=webhook,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_webhookresponse_event_data'),
    ]

    operations = [
        migrations.RunPython(migrate_custom_button_to_webhook)
    ]
