# Generated by Django 3.2.20 on 2023-08-01 19:29

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_auto_20230712_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='authorization_header',
            field=mirage.fields.EncryptedCharField(default=None, max_length=2000, null=True),
        ),
    ]
