# Generated by Django 3.2.20 on 2023-08-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0009_alter_webhook_authorization_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='append_full_response',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='append_to_alert_group',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='append_to_alert_group_template',
            field=models.TextField(default=None, null=True),
        ),
    ]
