# Generated by Django 3.2.19 on 2023-08-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0009_alter_webhook_authorization_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='append_full_response',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='append_to_alert_group',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='append_to_alert_group_template',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='trigger_type',
            field=models.IntegerField(choices=[(0, 'Escalation step'), (1, 'Alert Group Created'), (2, 'Acknowledged'), (3, 'Resolved'), (4, 'Silenced'), (5, 'Unsilenced'), (6, 'Unresolved'), (7, 'Unacknowledged')], default=0, null=True),
        ),
    ]
