# Generated by Django 3.2.19 on 2023-08-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_alter_webhook_trigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='append_full_response',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='append_to_alert_group',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='append_to_alert_group_template',
            field=models.TextField(default=None, null=True),
        ),
    ]
