# Generated by Django 3.2.20 on 2023-09-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_alter_webhook_trigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='preset',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
