# Generated by Django 4.2.10 on 2024-02-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_organization_is_grafana_labels_enabled'),
        ('webhooks', '0011_auto_20230920_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='user_management.team'),
        ),
    ]
