# Generated by Django 4.2.10 on 2024-02-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0014_webhook_filtered_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='is_from_connected_integration',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
