import { QueryVariable } from '@grafana/scenes';

import { Datasource } from './config';

const VARIABLES = [
  // Selectable
  new QueryVariable({
    text: 'grafanacloud-usage',
    value: 'grafanacloud-usage',
    hide: 0,
    includeAll: false,
    label: 'Data source',
    isMulti: false,
    name: 'datasource',
    options: [],
    query: 'prometheus',
    // queryValue: '',
    refresh: 1,
    regex: '',
    skipUrlSync: false,
    // type: 'datasource',
  }),
  new QueryVariable({
    name: 'instance',
    label: 'Instance',
    text: ['All'],
    value: ['$__all'],
    datasource: Datasource.GrafanaCloudPrometheus,
    definition: 'label_values(${alert_groups_total},slug)',
    hide: 0,
    includeAll: true,
    isMulti: true,
    options: [],
    query: {
      query: 'label_values(${alert_groups_total},slug)',
      refId: 'PrometheusVariableQueryEditor-VariableQuery',
    },
    refresh: 1,
    regex: '',
    skipUrlSync: false,
    sort: 0,
    type: 'query',
  }),
  new QueryVariable({
    name: 'team',
    label: 'Team',
    text: ['All'],
    value: ['$__all'],
    datasource: Datasource.GrafanaCloudPrometheus,
    definition: 'label_values(${alert_groups_total}{slug=~"$instance"},team)',
    hide: 0,
    includeAll: true,
    isMulti: true,
    options: [],
    query: {
      query: 'label_values(${alert_groups_total}{slug=~"$instance"},team)',
      refId: 'PrometheusVariableQueryEditor-VariableQuery',
    },
    refresh: 2,
    regex: '',
    skipUrlSync: false,
    sort: 0,
    type: 'query',
  }),
  new QueryVariable({
    name: 'integration',
    label: 'Integration',
    text: ['All'],
    value: ['$__all'],
    datasource: Datasource.GrafanaCloudPrometheus,
    definition: 'label_values(${alert_groups_total}{team=~"$team",slug=~"$instance"},integration)',
    hide: 0,
    includeAll: true,
    isMulti: true,
    options: [],
    query: {
      query: 'label_values(${alert_groups_total}{team=~"$team",slug=~"$instance"},integration)',
      refId: 'PrometheusVariableQueryEditor-VariableQuery',
    },
    refresh: 2,
    regex: '',
    skipUrlSync: false,
    sort: 0,
    type: 'query',
  }),

  // Non-Selectable
  new QueryVariable({
    name: 'alert_groups_total',
    label: 'alert_groups_total',
    datasource: Datasource.GrafanaCloudPrometheus,
    query: {
      query: 'metrics(alert_groups_total)',
      refId: 'PrometheusVariableQueryEditor-VariableQuery',
    },
    text: ['oncall_alert_groups_total', 'grafanacloud_oncall_instance_alert_groups_total'],
    value: ['oncall_alert_groups_total', 'grafanacloud_oncall_instance_alert_groups_total'],
    definition: 'metrics(alert_groups_total)',
    hide: 2,
    includeAll: false,
    isMulti: true,
    options: [],
    refresh: 1,
    regex: '',
    skipUrlSync: false,
    sort: 0,
    type: 'query',
  }),
  new QueryVariable({
    name: 'user_was_notified_of_alert_groups_total',
    label: 'user_was_notified_of_alert_groups_total',
    datasource: Datasource.GrafanaCloudPrometheus,
    definition: 'metrics(user_was_notified_of_alert_groups_total)',
    hide: 2,
    includeAll: false,
    isMulti: false,
    options: [],
    query: {
      query: 'metrics(user_was_notified_of_alert_groups_total)',
      refId: 'PrometheusVariableQueryEditor-VariableQuery',
    },
    refresh: 2,
    regex: '',
    skipUrlSync: false,
    sort: 0,
    type: 'query',
  }),
  new QueryVariable({
    name: 'alert_groups_response_time_seconds_bucket',
    label: 'alert_groups_response_time_seconds_bucket',
    datasource: Datasource.GrafanaCloudPrometheus,
    definition: 'metrics(alert_groups_response_time_seconds_bucket)',
    hide: 2,
    includeAll: false,
    isMulti: false,
    options: [],
    query: {
      query: 'metrics(alert_groups_response_time_seconds_bucket)',
      refId: 'PrometheusVariableQueryEditor-VariableQuery',
    },
    refresh: 1,
    regex: '',
    skipUrlSync: false,
    sort: 0,
    type: 'query',
  }),
  new QueryVariable({
    name: 'alert_groups_response_time_seconds_sum',
    label: 'alert_groups_response_time_seconds_sum',
    datasource: Datasource.GrafanaCloudPrometheus,
    definition: 'metrics(alert_groups_response_time_seconds_sum)',
    hide: 2,
    includeAll: false,
    isMulti: false,
    options: [],
    query: {
      query: 'metrics(alert_groups_response_time_seconds_sum)',
      refId: 'PrometheusVariableQueryEditor-VariableQuery',
    },
    refresh: 1,
    regex: '',
    skipUrlSync: false,
    sort: 0,
    type: 'query',
  }),
  new QueryVariable({
    name: 'alert_groups_response_time_seconds_count',
    label: 'alert_groups_response_time_seconds_count',
    datasource: Datasource.GrafanaCloudPrometheus,
    definition: 'metrics(alert_groups_response_time_seconds_count)',
    hide: 2,
    includeAll: false,
    isMulti: false,
    options: [],
    query: {
      query: 'metrics(alert_groups_response_time_seconds_count)',
      refId: 'PrometheusVariableQueryEditor-VariableQuery',
    },
    refresh: 1,
    regex: '',
    skipUrlSync: false,
    sort: 0,
    type: 'query',
  }),
];

export default VARIABLES;
