# Generated by Django 3.2.19 on 2023-07-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('phone_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliyunDyvmsPhoneCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('call_id', models.CharField(blank=True, max_length=50)),
                ('phone_call_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                           related_name='aliyun_dyvms_aliyundyvmsphonecall_related',
                                                           related_query_name='aliyun_dyvms_aliyunphonecall',
                                                           to='phone_notifications.phonecallrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
