apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
