{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oncall.engine.fullname" . }}-external
  labels:
    {{- include "oncall.engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oncall.engine.selectorLabels" . | nindent 4 }}
{{- end }}