apiVersion: v1
kind: Service
metadata:
  name: {{ include "oncall.engine.fullname" . }}
  labels:
    {{- include "oncall.engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oncall.engine.selectorLabels" . | nindent 4 }}
