import { addCustomSchemasToAutogeneratedOutput } from './generate-types.utils';

describe('addCustomSchemasToAutogeneratedOutput()', () => {
  it('adds custom schemas to original output correctly', () => {
    const ORIGINAL_OUTPUT = `
        export interface components {
            schemas: {
                Alert: {
                    readonly id: string;
                    /** Format: uri */
                    link_to_upstream_details?: string | null;
                    readonly render_for_web: string;
                    /** Format: date-time */
                    readonly created_at: string;
                };
                AlertGroup: {
                    name: string;
                };
                Schedule: {
                    id: string;
                };
            };
        };
    `;
    expect(addCustomSchemasToAutogeneratedOutput(ORIGINAL_OUTPUT, ['AlertGroup', 'Schedule'])).toMatchInlineSnapshot(`
      "
            import type { CustomApiSchemas } from './types-generator/custom-schemas';
        
            
              export interface components {
                  schemas: {
                      Alert: {
                          readonly id: string;
                          /** Format: uri */
                          link_to_upstream_details?: string | null;
                          readonly render_for_web: string;
                          /** Format: date-time */
                          readonly created_at: string;
                      };
                      AlertGroup: CustomApiSchemas[\\"AlertGroup\\"] &  {
                          name: string;
                      };
                      Schedule: CustomApiSchemas[\\"Schedule\\"] &  {
                          id: string;
                      };
                  };
              };
          
          "
    `);
  });
});
