AUTH_TOKEN_CHARACTER_LENGTH = 64
AUTH_SHORT_TOKEN_CHARACTER_LENGTH = 6
TOKEN_KEY_LENGTH = 8
DIGEST_LENGTH = 128
MAX_PUBLIC_API_TOKENS_PER_USER = 5

SLACK_AUTH_TOKEN_NAME = "slack_login_token"

SCHEDULE_EXPORT_TOKEN_NAME = "token"
SCHEDULE_EXPORT_TOKEN_CHARACTER_LENGTH = 32
