inputs:
  python-dependency-paths:
    description: "The path(s) to the Python dependency file(s) to install"
    required: false
    default: "engine/requirements.txt engine/requirements-dev.txt"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.4"
        cache: "pip"
        cache-dependency-path: ${{ inputs.python-dependency-paths }}
