# Generated by Django 3.2.5 on 2022-05-31 14:46

from django.db import migrations, models
import uuid
import django_migration_linter as linter


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.CreateModel(
            name='CloudHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(max_length=50)),
                ('integration_url', models.URLField()),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OssInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('report_sent_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CloudUserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('cloud_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
