label = "OnCall.Plugin"

is_ci=config.tilt_subcommand == "ci"
grafana_plugin_dir="../../grafana-plugin"

# On CI dependencies are installed separately so we just build prod bundle to be consumed by Grafana dev server
if is_ci:
    local_resource(
        "build-ui",
        labels=[label],
        dir=grafana_plugin_dir,
        cmd="yarn build",
        allow_parallel=True,
    )

create_irm_plugin_ui_k8s_resources("oncall", k8s_namespace="default")
