FROM node:18.16.0-alpine

WORKDIR /etc/app
ENV PATH /etc/app/node_modules/.bin:$PATH

# this allows hot reloading of the container
# https://stackoverflow.com/a/72478714
ENV WATCHPACK_POLLING true

# installs dependencies for running playwright e2e integration tests
RUN npx playwright install

CMD ["yarn", "start"]
