export const logoCoors: { [key: string]: { x: number; y: number } } = {
  grafana: { x: 9, y: 0 },
  grafana_alerting: { x: 9, y: 0 },
  legacy_grafana_alerting: { x: 9, y: 0 },
  webhook: { x: 2, y: 14 },
  alertmanager: { x: 12, y: 4 },
  legacy_alertmanager: { x: 12, y: 4 },
  kapacitor: { x: 10, y: 1 },
  fabric: { x: 8, y: 7 },
  newrelic: { x: 0, y: 11 },
  datadog: { x: 3, y: 7 },
  pagerduty: { x: 3, y: 1 },
  pingdom: { x: 4, y: 0 },
  elastalert: { x: 2, y: 1 },
  amazon_sns: { x: 0, y: 2 },
  curler: { x: 0, y: 0 },
  sentry: { x: 11, y: 12 },
  formatted_webhook: { x: 2, y: 14 },
  heartbeat_monitoring: { x: 2, y: 14 },
  Stackdriver: { x: 8, y: 8 },
  uptimerobot: { x: 14, y: 8 },
  zabbix: { x: 7, y: 14 },
  prtg: { x: 12, y: 5 },
  jira: { x: 8, y: 9 },
  zendesk: { x: 9, y: 14 },
  appdynamics: { x: 3, y: 3 },
};
