# Generated by Django 3.2.18 on 2023-03-21 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_organization_cluster_slug'),
        ('mobile_app', '0002_alter_mobileappauthtoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_notification_sound_name', models.CharField(default='default_sound', max_length=100)),
                ('default_notification_volume_type', models.CharField(choices=[('constant', 'Constant'), ('intensifying', 'Intensifying')], default='constant', max_length=50)),
                ('default_notification_volume', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('default_notification_volume_override', models.BooleanField(default=False)),
                ('important_notification_sound_name', models.CharField(default='default_sound_important', max_length=100)),
                ('important_notification_volume_type', models.CharField(choices=[('constant', 'Constant'), ('intensifying', 'Intensifying')], default='constant', max_length=50)),
                ('important_notification_volume', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('important_notification_override_dnd', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
            ],
        ),
    ]
