# Generated by Django 3.2.18 on 2023-04-25 10:33

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0003_mobileappusersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappusersettings',
            name='info_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        # migrations.AddField enforces the default value on the app level, which leads to the issues during release
        # adding same default value on the database level
        AddDefaultValue(
            model_name='mobileappusersettings',
            name='info_notifications_enabled',
            value=True,
        ),

        migrations.AddField(
            model_name='mobileappusersettings',
            name='going_oncall_notification_timing',
            field=models.IntegerField(choices=[(43200, 'twelve hours before'), (86400, 'one day before'), (604800, 'one week before')], default=43200),
        ),
        # migrations.AddField enforces the default value on the app level, which leads to the issues during release
        # adding same default value on the database level
        AddDefaultValue(
            model_name='mobileappusersettings',
            name='going_oncall_notification_timing',
            value=43200,
        ),
    ]
