# Generated by Django 3.2.18 on 2023-05-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0004_auto_20230425_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappusersettings',
            name='important_notification_volume_override',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
