# Generated by Django 3.2.19 on 2023-05-12 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0005_mobileappusersettings_important_notification_volume_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappusersettings',
            name='info_notification_sound_name',
            field=models.CharField(default='default_sound', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobileappusersettings',
            name='info_notification_volume',
            field=models.FloatField(default=0.8, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='mobileappusersettings',
            name='info_notification_volume_override',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='mobileappusersettings',
            name='info_notification_volume_type',
            field=models.CharField(choices=[('constant', 'Constant'), ('intensifying', 'Intensifying')], default='constant', max_length=50, null=True),
        ),
    ]
