# Generated by Django 3.2.18 on 2023-05-12 09:29

from django.db import migrations, models


def set_info_notifications_enabled_to_false(apps, schema_editor):
    MobileAppUserSettings = apps.get_model("mobile_app", "MobileAppUserSettings")
    MobileAppUserSettings.objects.all().update(info_notifications_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0006_auto_20230512_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappusersettings',
            name='info_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_info_notifications_enabled_to_false, migrations.RunPython.noop),
    ]
