# Generated by Django 3.2.19 on 2023-07-05 16:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0009_alter_fcmdevice_user'),
        ('mobile_app', '0008_mobileappusersettings_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fcm_django.fcmdevice',),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
