# Generated by Django 3.2.19 on 2023-07-05 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0009_alter_fcmdevice_user'),
        ('mobile_app', '0008_mobileappusersettings_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('fcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fcm_django.fcmdevice')),
            ],
            options={
                'verbose_name': 'FCM device',
                'abstract': False,
            },
            bases=('fcm_django.fcmdevice',),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
