# Generated by Django 3.2.20 on 2023-07-20 14:53

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0009_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileappusersettings',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        # migrations.AddField enforces the default value on the app level, which leads to the issues during release
        # adding same default value on the database level
        AddDefaultValue(
            model_name='mobileappusersettings',
            name='time_zone',
            value='UTC',
        ),
    ]
