# Generated by Django 3.2.20 on 2023-10-30 09:25

import apps.mobile_app.models
import django_migration_linter as linter

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0010_mobileappusersettings_time_zone'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name='mobileappusersettings',
            name='going_oncall_notification_timing',
        ),
        migrations.AddField(
            model_name='mobileappusersettings',
            name='going_oncall_notification_timing',
            field=models.JSONField(default=apps.mobile_app.models.default_notification_timing_options),
        ),
    ]
