# Generated by Django 3.2.20 on 2023-10-30 09:25

import apps.mobile_app.models
from django.db import migrations, models
from apps.mobile_app.models import default_notification_timing_options


def set_going_oncall_notification_timing_to_default(apps, schema_editor):
    MobileAppUserSettings = apps.get_model("mobile_app", "MobileAppUserSettings")
    default = default_notification_timing_options()
    MobileAppUserSettings.objects.all().update(going_oncall_notification_timing=default)


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0010_mobileappusersettings_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileappusersettings',
            name='going_oncall_notification_timing',
            field=models.JSONField(default=apps.mobile_app.models.default_notification_timing_options),
        ),
        migrations.RunPython(set_going_oncall_notification_timing_to_default, migrations.RunPython.noop),
    ]
