import typing

from django.db.models import TextChoices

from apps.user_management.types import AlertGroupTableColumn


class AlertGroupTableDefaultColumnChoices(TextChoices):
    STATUS = "status", "Status"
    ID = "id", "ID"
    TITLE = "title", "Title"
    ALERTS = "alerts", "Alerts"
    INTEGRATION = "integration", "Integration"
    CREATED = "created", "Created"
    LABELS = "labels", "Labels"
    TEAM = "team", "Team"
    USERS = "users", "Users"


class AlertGroupTableColumnTypeChoices(TextChoices):
    DEFAULT = "default"
    LABEL = "label"


def default_columns() -> typing.List[AlertGroupTableColumn]:
    return [
        {"name": column.label, "id": column.value, "type": AlertGroupTableColumnTypeChoices.DEFAULT.value}
        for column in AlertGroupTableDefaultColumnChoices
    ]


class GoogleCalendarSettings(typing.TypedDict):
    oncall_schedules_to_consider_for_shift_swaps: typing.Optional[typing.List[str]]
    """
    `public_primary_key` of specific OnCall schedules that should be considered for autogenerated shift swap requests.
    """
