# Generated by Django 4.2.6 on 2023-10-31 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_notifications', '0001_initial'),
        ('zvonok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zvonokphonecall',
            name='phone_call_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='phone_notifications.phonecallrecord'),
        ),
    ]
