# Generated by Django 4.2.15 on 2024-11-26 12:42

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_labelkeycache_prescribed_labelvaluecache_prescribed'),
    ]

    operations = [
        linter.IgnoreMigration(),  # this field is deprecated
        migrations.RemoveField(
            model_name='alertreceivechannelassociatedlabel',
            name='inheritable',
        ),
    ]
