# Generated by Django 4.2.15 on 2024-11-26 13:37

from django.db import migrations

import common.migrations.remove_field


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0006_remove_alertreceivechannelassociatedlabel_inheritable_state"),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldDB(
            model_name="AlertReceiveChannelAssociatedLabel",
            name="inheritable",
            remove_state_migration=("labels", "0007_remove_alertreceivechannelassociatedlabel_inheritable_state"),
        ),
    ]
