name: Install frontend dependencies
description: Setup node/pnpm + install frontend dependencies
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.1.4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.15.1
        cache: pnpm
        cache-dependency-path: grafana-plugin/pnpm-lock.yaml
    - name: Install frontend dependencies
      shell: bash
      working-directory: grafana-plugin
      run: pnpm install --frozen-lockfile --prefer-offline
