# Generated by Django 4.2.27 on 2026-02-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='zoommessage',
            new_name='zoom_zoomme_channel_6d9a58_idx',
            old_name='zoom_zoomme_channel_idx',
        ),
        migrations.RenameIndex(
            model_name='zoomuser',
            new_name='zoom_zoomus_zoom_us_a37e7a_idx',
            old_name='zoom_zoomus_zoom_us_idx',
        ),
    ]
