# Generated by Django 3.2.5 on 2021-08-04 10:51

import sys
from django.db import migrations
from apps.public_api import constants as public_api_constants


def create_demo_token_instances(apps, schema_editor):
    if not (len(sys.argv) > 1 and sys.argv[1] == 'test'):
        SlackUserIdentity = apps.get_model('slack', 'SlackUserIdentity')
        SlackTeamIdentity = apps.get_model('slack', 'SlackTeamIdentity')
        SlackChannel = apps.get_model('slack', 'SlackChannel')
        SlackUserGroup = apps.get_model("slack", "SlackUserGroup")

        slack_team_identity, _ = SlackTeamIdentity.objects.get_or_create(
            slack_id=public_api_constants.DEMO_SLACK_TEAM_ID,
        )
        SlackUserIdentity.objects.get_or_create(
            slack_id=public_api_constants.DEMO_SLACK_USER_ID,
            slack_team_identity=slack_team_identity,
        )

        SlackChannel.objects.get_or_create(
            name=public_api_constants.DEMO_SLACK_CHANNEL_NAME,
            slack_id=public_api_constants.DEMO_SLACK_CHANNEL_SLACK_ID,
            slack_team_identity=slack_team_identity,
        )

        SlackUserGroup.objects.get_or_create(
            slack_team_identity=slack_team_identity,
            slack_id=public_api_constants.DEMO_SLACK_USER_GROUP_SLACK_ID,
            public_primary_key=public_api_constants.DEMO_SLACK_USER_GROUP_ID,
            name=public_api_constants.DEMO_SLACK_USER_GROUP_NAME,
            handle=public_api_constants.DEMO_SLACK_USER_GROUP_HANDLE,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_squashed_initial'),
    ]

    operations = [
        migrations.RunPython(create_demo_token_instances, migrations.RunPython.noop)
    ]
