# Generated by Django 3.2.19 on 2023-06-13 08:59

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_squashed_initial'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.DeleteModel(
            name='SlackActionRecord',
        ),
    ]
