# Generated by Django 4.2.11 on 2024-07-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_auto_20230913_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackteamidentity',
            name='_unified_slack_app_installed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
