# Generated by Django 4.2.16 on 2024-11-22 12:36

from django.db import migrations, models
import django.db.models.deletion
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_slackteamidentity__unified_slack_app_installed'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RenameField(
            model_name='slackmessage',
            old_name='channel_id',
            new_name='_channel_id',
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_messages', to='slack.slackchannel'),
        ),
    ]
