# Generated by Django 4.2.16 on 2024-12-04 12:00

import common.migrations.remove_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0007_migrate_slackmessage_channel_id'),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldState(
            model_name='SlackMessage',
            name='active_update_task_id',
        ),
    ]
