# Generated by Django 4.2.16 on 2024-12-04 21:17

import logging

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F
import django_migration_linter as linter

logger = logging.getLogger(__name__)


def drop_orphaned_slack_messages(apps, schema_editor):
    """
    At this point, in the 0007_migrate_slackmessage_channel_id migration, we have already migrated the old
    SlackMessage._channel_id (char field) to the new SlackMessage.channel_id (FK field).

    This script is needed to identity, and drop, SlackMessage records that are "orphaned". This would've occured in two
    cases:
    - the organization switched their Slack team identity. We have historically never done clean-up of the old SlackMessage records
    - a Slack channel was deleted. Previously, we did not have a FK constraint on the SlackMessage._channel_id
    char field, so there was no CASCADE delete behaviour (now there is).

    In both of these scenarios, the SlackMessage records would be "orphaned" - they would have a non-null channel_id
    foreign key relationship, which prevents us from setting NOT NULL constraint on the channel_id field.
    """
    SlackMessage = apps.get_model("slack", "SlackMessage")

    logger.info("Starting migration to drop orphaned SlackMessage records.")

    slack_messages = SlackMessage.objects.filter(channel_id__isnull=True)

    total_messages = slack_messages.count()
    if total_messages == 0:
        logger.info("No orphaned SlackMessages need to be dropped.")
        return

    logger.info(f"Found {total_messages} orphaned SlackMessages to drop.")

    slack_messages.delete()

    logger.info("Finished migration to drop orphaned SlackMessages.")


def fill_in_missing_slack_team_identity_values(apps, schema_editor):
    """
    This migration is needed to fill in the missing `slack_team_identity` field for SlackMessage records that were
    created before the field was added. This field is required for the SlackMessage model to be valid, and it is
    required for the SlackMessage model to be able to be associated with a SlackChannel model.
    """
    SlackMessage = apps.get_model("slack", "SlackMessage")

    logger.info("Starting migration to fill in missing SlackMessage.slack_team_identity values")

    slack_messages = SlackMessage.objects.filter(slack_team_identity__isnull=True)

    total_messages = slack_messages.count()
    if total_messages == 0:
        logger.info("No missing SlackMessage.slack_team_identity values")
        return

    logger.info(f"Found {total_messages} SlackMessages which have missing slack_team_identity values.")

    # Update SlackMessages where slack_channel and slack_channel.slack_team_identity are available
    updated_count = slack_messages.filter(
        slack_channel__isnull=False,
        slack_channel__slack_team_identity__isnull=False
    ).update(
        slack_team_identity=F('slack_channel__slack_team_identity')
    )

    logger.info(f"Updated {updated_count} SlackMessages with slack_team_identity from slack_channel.")

    # Check if there are any SlackMessages that couldn't be updated
    remaining_messages = slack_messages.filter(slack_team_identity__isnull=True)
    remaining_count = remaining_messages.count()

    if remaining_count > 0:
        logger.warning(
            f"{remaining_count} SlackMessages could not be updated because slack_channel or slack_channel.slack_team_identity is missing."
        )

    logger.info("Finished migration to fill in missing SlackMessage.slack_team_identity values")


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0008_remove_slackmessage_active_update_task_id_state'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RenameField(
            model_name='slackmessage',
            old_name='_slack_team_identity',
            new_name='slack_team_identity',
        ),
        migrations.RunPython(drop_orphaned_slack_messages, migrations.RunPython.noop),
        migrations.RunPython(fill_in_missing_slack_team_identity_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='slackmessage',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='slack_messages', to='slack.slackchannel'),
        ),
    ]
