# Generated by Django 4.2.17 on 2024-12-06 17:05

import common.migrations.remove_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0011_remove_slackmessage__channel_id_state'),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldState(
            model_name='SlackMessage',
            name='organization',
        ),
    ]
