# Generated by Django 3.2.18 on 2023-04-08 07:11

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('twilioapp', '0002_auto_20220604_1008'),
    ]

    database_operations = [
        migrations.AlterModelTable('PhoneCall', 'phone_notifications_phonecallrecord'),
        migrations.AlterModelTable('SMSMessage', 'phone_notifications_smsrecord')
    ]

    state_operations = [
        migrations.DeleteModel('PhoneCall'),
        migrations.DeleteModel('SMSMessage')
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
