# Generated by Django 3.2.18 on 2023-05-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('twilioapp', '0002_auto_20220604_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_sid', models.CharField(max_length=64, unique=True)),
                ('auth_token', models.CharField(default=None, max_length=64, null=True)),
                ('api_key_sid', models.CharField(default=None, max_length=64, null=True)),
                ('api_key_secret', models.CharField(default=None, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwilioSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('country_code', models.CharField(default=None, max_length=16, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_sender', to='twilioapp.twilioaccount')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_twilioapp.twiliosender_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TwilioPhoneCallSender',
            fields=[
                ('twiliosender_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twilioapp.twiliosender')),
                ('number', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('twilioapp.twiliosender',),
        ),
        migrations.CreateModel(
            name='TwilioSmsSender',
            fields=[
                ('twiliosender_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twilioapp.twiliosender')),
                ('sender', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('twilioapp.twiliosender',),
        ),
        migrations.CreateModel(
            name='TwilioVerificationSender',
            fields=[
                ('twiliosender_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twilioapp.twiliosender')),
                ('verify_service_sid', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('twilioapp.twiliosender',),
        ),
    ]
