# Generated by Django 4.2.6 on 2023-10-31 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_notifications', '0001_initial'),
        ('twilioapp', '0007_delete_twiliologrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliophonecallsender',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_account', to='twilioapp.twilioaccount'),
        ),
        migrations.AlterField(
            model_name='twiliosms',
            name='sms_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='phone_notifications.smsrecord'),
        ),
        migrations.AlterField(
            model_name='twiliosmssender',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_account', to='twilioapp.twilioaccount'),
        ),
        migrations.AlterField(
            model_name='twilioverificationsender',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_account', to='twilioapp.twilioaccount'),
        ),
    ]
