from django.utils import dateparse

DEMO_USER_ID = "U4DNY931HHJS5"
DEMO_ORGANIZATION_ID = "TCNPY4A1BWUMP"
DEMO_SLACK_USER_ID = "UALEXSLACKDJPK"
DEMO_SLACK_TEAM_ID = "TALEXSLACKDJPK"
DEMO_AUTH_TOKEN = "meowmeowmeow"
DEMO_USER_USERNAME = "Alex"
DEMO_USER_EMAIL = "public-api-demo-user-1@amixr.io"
DEMO_INTEGRATION_ID = "CFRPV98RPR1U8"
DEMO_INTEGRATION_LINK_TOKEN = "mReAoNwDm0eMwKo1mTeTwYo"
DEMO_INTEGRATION_NAME = "Grafana :blush:"
DEMO_ROUTE_ID_1 = "RIYGUJXCPFHXY"
DEMO_ROUTE_ID_2 = "RVBE4RKQSCGJ2"
DEMO_SLACK_CHANNEL_FOR_ROUTE_ID = "CH23212D"
DEMO_ESCALATION_CHAIN_ID = "F5JU6KJET33FE"
DEMO_ESCALATION_POLICY_ID_1 = "E3GA6SJETWWJS"
DEMO_ESCALATION_POLICY_ID_2 = "E5JJTU52M5YM4"
DEMO_SCHEDULE_ID_ICAL = "SBM7DV7BKFUYU"
DEMO_SCHEDULE_ID_CALENDAR = "S3Z477AHDXTMF"
DEMO_SCHEDULE_NAME_ICAL = "Demo schedule iCal"
DEMO_SCHEDULE_NAME_CALENDAR = "Demo schedule Calendar"
DEMO_SCHEDULE_ICAL_URL_PRIMARY = "https://example.com/meow_calendar.ics"
DEMO_SCHEDULE_ICAL_URL_OVERRIDES = "https://example.com/meow_calendar_overrides.ics"
DEMO_INCIDENT_ID = "I68T24C13IFW1"
DEMO_INCIDENT_CREATED_AT = "2020-05-19T12:37:01.430444Z"
DEMO_INCIDENT_RESOLVED_AT = "2020-05-19T13:37:01.429805Z"
DEMO_ALERT_IDS = [
    ("AA74DN7T4JQB6", "2020-05-11T20:07:43Z"),
    ("AR9SSYFKE2PV7", "2020-05-11T20:07:54Z"),
    ("AWJQSGEYYUFGH", "2020-05-11T20:07:58Z"),
]
DEMO_ALERT_PAYLOAD = {
    "evalMatches": [
        {"value": 100, "metric": "High value", "tags": None},
        {"value": 200, "metric": "Higher Value", "tags": None},
    ],
    "message": "Someone is testing the alert notification within grafana.",
    "ruleId": 0,
    "ruleName": "Test notification",
    "ruleUrl": "https://amixr.io/",
    "state": "alerting",
    "title": "[Alerting] Test notification",
}
VALID_DATE_FOR_DELETE_INCIDENT = dateparse.parse_date("2020-07-04")
DEMO_SLACK_CHANNEL_NAME = "meow_channel"
DEMO_SLACK_CHANNEL_SLACK_ID = "MEOW_SLACK_ID"
DEMO_PERSONAL_NOTIFICATION_ID_1 = "NT79GA9I7E4DJ"
DEMO_PERSONAL_NOTIFICATION_ID_2 = "ND9EHN5LN1DUU"
DEMO_PERSONAL_NOTIFICATION_ID_3 = "NEF49YQ1HNPDD"
DEMO_PERSONAL_NOTIFICATION_ID_4 = "NWAL6WFJNWDD8"
DEMO_RESOLUTION_NOTE_ID = "M4BTQUS3PRHYQ"
DEMO_RESOLUTION_NOTE_TEXT = "Demo resolution note"
DEMO_RESOLUTION_NOTE_CREATED_AT = "2020-06-19T12:40:01.429805Z"
DEMO_RESOLUTION_NOTE_SOURCE = "web"
DEMO_CUSTOM_ACTION_ID = "KGEFG74LU1D8L"
DEMO_CUSTOM_ACTION_NAME = "Publish Incident To Jira"
DEMO_SLACK_USER_GROUP_ID = "GPFAPH7J7BKJB"
DEMO_SLACK_USER_GROUP_SLACK_ID = "MEOW_SLACK_ID"
DEMO_SLACK_USER_GROUP_NAME = "Meow Group"
DEMO_SLACK_USER_GROUP_HANDLE = "meow_group"
DEMO_ON_CALL_SHIFT_ID_1 = "OH3V5FYQEYJ6M"
DEMO_ON_CALL_SHIFT_ID_2 = "O9WTH7CKM3KZW"
DEMO_ON_CALL_SHIFT_NAME_1 = "Demo single event"
DEMO_ON_CALL_SHIFT_NAME_2 = "Demo recurrent event"
DEMO_ON_CALL_SHIFT_START_1 = "2020-09-10T08:00:00"
DEMO_ON_CALL_SHIFT_START_2 = "2020-09-10T16:00:00"
DEMO_ON_CALL_SHIFT_DURATION = 10800
DEMO_ON_CALL_SHIFT_BY_DAY = ["MO", "WE", "FR"]
