import { AlertGroup as AutogeneratedAlertGroup } from 'network/api/autogenerated/onCallApiSchemas';

declare module 'network/api/autogenerated/onCallApiSchemas' {
  type AlertGroup = AutogeneratedAlertGroup & {
    customProp: string;
  };
}
