# Generated by Django 3.2.5 on 2022-05-31 14:46

from django.db import migrations, models
import django.db.models.deletion
import django_migration_linter as linter


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_squashed_initial'),
        ('schedules', '0001_squashed_initial'),
        ('auth_token', '0001_squashed_initial'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name='userscheduleexportauthtoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule_export_token', to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='userscheduleexportauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_schedule_export_token', to='user_management.user'),
        ),
        migrations.AddField(
            model_name='slackauthtoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_auth_token_set', to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='slackauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_auth_token_set', to='user_management.user'),
        ),
        migrations.AddField(
            model_name='scheduleexportauthtoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_export_token', to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='scheduleexportauthtoken',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_export_token', to='schedules.oncallschedule'),
        ),
        migrations.AddField(
            model_name='scheduleexportauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_export_token', to='user_management.user'),
        ),
        migrations.AddField(
            model_name='pluginauthtoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='mobileappverificationtoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_app_verification_token_set', to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='mobileappverificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_app_verification_token_set', to='user_management.user'),
        ),
        migrations.AddField(
            model_name='mobileappauthtoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_app_auth_tokens', to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='mobileappauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_app_auth_tokens', to='user_management.user'),
        ),
        migrations.AddField(
            model_name='apiauthtoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='apiauthtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='user_management.user'),
        ),
        migrations.AlterUniqueTogether(
            name='userscheduleexportauthtoken',
            unique_together={('user', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleexportauthtoken',
            unique_together={('user', 'organization', 'schedule')},
        ),
    ]
