# Generated by Django 3.2.16 on 2022-11-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_token', '0002_squashed_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileappverificationtoken',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='mobileappverificationtoken',
            name='user',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='MobileAppAuthToken',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='MobileAppAuthToken',
                    table='mobile_app_mobileappauthtoken',
                ),
            ],
        ),
        migrations.DeleteModel(
            name='MobileAppVerificationToken',
        ),
    ]
