# Generated by Django 3.2.19 on 2023-07-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20230411_1358'),
        ('auth_token', '0003_auto_20221121_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginauthtoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_auth_tokens', to='user_management.organization'),
        ),
    ]
