# Generated by Django 4.2.10 on 2024-03-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0047_alertreceivechannel_additional_settings'),
        ('user_management', '0020_organization_is_grafana_labels_enabled'),
        ('auth_token', '0004_alter_pluginauthtoken_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationBacksyncAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.CharField(db_index=True, max_length=8)),
                ('digest', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('alert_receive_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='alerts.alertreceivechannel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_auth_tokens', to='user_management.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
