# Substituting bitnami image with official image
# to be able to run Rabbitmq on arm64 (Mac M1)
# Optional for amd64 systems
rabbitmq:
  enabled: true
  image:
    repository: rabbitmq
    tag: 3.10.10
  auth:
    username: user
    password: user
  extraEnvVars:
    - name: RABBITMQ_DEFAULT_USER
      value: user
    - name: RABBITMQ_DEFAULT_PASS
      value: user