EVENT_SUMMARY_IGNORE_KEYWORD = "#grafana-oncall-ignore"

GOOGLE_CALENDAR_EVENT_DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"
"""
https://stackoverflow.com/a/17159470/3902555
"""

DAYS_IN_FUTURE_TO_CONSIDER_OUT_OF_OFFICE_EVENTS = 30
