# NOTE: I'm temporarily leaving this migration file here, it will very soon be moved to the migrations folder
# see this conversation for context
# https://raintank-corp.slack.com/archives/C06K1MQ07GS/p1732555465144099

# Generated by Django 4.2.16 on 2024-11-01 10:58
import logging

from django.conf import settings
from django.db import migrations
import django_migration_linter as linter

logger = logging.getLogger(__name__)

def populate_slack_channel(apps, schema_editor):
    SlackMessage = apps.get_model("slack", "SlackMessage")
    SlackChannel = apps.get_model("slack", "SlackChannel")

    logger.info("Starting migration to populate channel field.")

    db_type = getattr(settings, "DATABASE_TYPE", None)

    if db_type == settings.DATABASE_TYPES.POSTGRESQL:
        sql = f"""
        UPDATE {SlackMessage._meta.db_table} AS sm
        SET channel_id = sc.id
        FROM {SlackChannel._meta.db_table} AS sc
        WHERE sc.slack_id = sm._channel_id
          AND sc.slack_team_identity_id = sm.slack_team_identity
          AND sm._channel_id IS NOT NULL
          AND sm.slack_team_identity IS NOT NULL;
        """
    elif db_type == settings.DATABASE_TYPES.SQLITE3:
        sql = f"""
        UPDATE {SlackMessage._meta.db_table}
        SET channel_id = (
            SELECT sc.id
            FROM {SlackChannel._meta.db_table} AS sc
            WHERE sc.slack_id = {SlackMessage._meta.db_table}._channel_id
              AND sc.slack_team_identity_id = {SlackMessage._meta.db_table}.slack_team_identity
        )
        WHERE _channel_id IS NOT NULL
          AND slack_team_identity IS NOT NULL
          AND EXISTS (
              SELECT 1
              FROM {SlackChannel._meta.db_table} AS sc
              WHERE sc.slack_id = {SlackMessage._meta.db_table}._channel_id
                AND sc.slack_team_identity_id = {SlackMessage._meta.db_table}.slack_team_identity
          );
        """
    elif db_type == settings.DATABASE_TYPES.MYSQL:
        sql = f"""
        UPDATE
            {SlackMessage._meta.db_table} AS sm
        JOIN {SlackChannel._meta.db_table} AS sc
            ON sc.slack_id = sm._channel_id
            AND sc.slack_team_identity_id = sm.slack_team_identity
        SET
            sm.channel_id = sc.id
        WHERE
            sm._channel_id IS NOT NULL
            AND sm.slack_team_identity IS NOT NULL;
        """

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql)
        updated_rows = cursor.rowcount  # Number of rows updated

    logger.info(f"Bulk updated {updated_rows} SlackMessages with their Slack channel.")
    logger.info("Finished migration to populate channel field.")

class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0006_rename_channel_id_slackmessage__channel_id_and_more'),
    ]

    operations = [
        # Simply setting this new field is okay; we are not deleting the value of _channel_id
        # Therefore, no need to revert it
        linter.IgnoreMigration(),
        migrations.RunPython(populate_slack_channel, migrations.RunPython.noop),
    ]
