# NOTE: this is being left in this directory on purpose, it will be moved to apps/alerts/migrations
# in a separate PR/release
#
# Generated by Django 4.2.16 on 2024-12-04 12:00

from django.db import migrations

import common.migrations.remove_field


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0008_remove_slackmessage_active_update_task_id_state"),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldDB(
            model_name="SlackMessage",
            name="active_update_task_id",
            remove_state_migration=("slack", "0008_remove_slackmessage_active_update_task_id_state"),
        ),
    ]
