# Generated by Django 3.2.13 on 2022-06-14 15:18

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_squashed_initial'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name='grafanaalertingcontactpoint',
            name='datasource_uid',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
