# Generated by Django 3.2.13 on 2022-07-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_grafanaalertingcontactpoint_datasource_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertgroup',
            name='active_cache_for_web_calculation_id',
        ),
        migrations.RemoveField(
            model_name='alertgroup',
            name='cached_render_for_web',
        ),
    ]
