# Generated by Django 3.2.13 on 2022-07-27 10:51

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alertgroup_cached_render_for_web'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddIndex(
            model_name='alertgroup',
            index=models.Index(fields=['channel_id', 'resolved', 'acknowledged', 'silenced', 'root_alert_group_id', 'is_archived'], name='alerts_aler_channel_ee84a7_idx'),
        ),
    ]
