# Generated by Django 3.2.15 on 2022-09-01 16:54

from django.db import migrations

from apps.alerts.models import AlertReceiveChannel
from apps.alerts.tasks import update_verbose_name_for_alert_receive_channel


def populate_verbose_name(apps, _):
    pks = AlertReceiveChannel.objects_with_deleted.values_list("pk", flat=True)
    for pk in pks:
        update_verbose_name_for_alert_receive_channel.delay(pk)


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alertgroup_alerts_aler_channel_ee84a7_idx'),
    ]

    operations = [
        migrations.RunPython(populate_verbose_name, migrations.RunPython.noop),
    ]
