# Generated by Django 3.2.13 on 2022-10-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_populate_web_title_cache'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='alert',
            index_together={('group', 'created_at')},
        ),
    ]
