# Generated by Django 3.2.16 on 2023-01-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alter_alertgrouplogrecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreceivechannel',
            name='web_templates_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
