# Generated by Django 3.2.17 on 2023-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alertreceivechannel_web_templates_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelfilter',
            name='filtering_term_jinja2',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='channelfilter',
            name='filtering_term_type',
            field=models.IntegerField(choices=[(0, 'regex'), (1, 'jinja2')], default=None, null=True),
        ),
    ]
