# Generated by Django 3.2.17 on 2023-03-07 07:27

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alertreceivechannel_web_templates_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelfilter',
            name='filtering_term_type',
            field=models.IntegerField(choices=[(0, 'regex'), (1, 'jinja2')], default=0),
        ),
        # migrations.AddField enforces the default value on the app level, which leads to the issues during release
        # adding same default value on the database level
        AddDefaultValue(
            model_name='channelfilter',
            name='filtering_term_type',
            value=0
        )
    ]
