# Generated by Django 3.2.18 on 2023-03-28 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_channelfilter_filtering_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='is_restricted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='alertreceivechannel',
            name='alert_groups_created_counter_current_month',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='alertreceivechannel',
            name='alert_groups_created_this_month',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
