# Generated by Django 3.2.18 on 2023-04-11 02:48

from django.db import migrations, models

def combine_names(apps, schema_editor):
    ChannelFilter = apps.get_model("alerts", "ChannelFilter")
    for route in ChannelFilter.objects.all():
        if route.filtering_term_type == ChannelFilter.FILTERING_TERM_TYPE_REGEX:
            route.routing_template = f'{{ payload | json_dumps | regex_search("{route.filtering_term}") }}'
        elif route.filtering_term_type == ChannelFilter.FILTERING_TERM_TYPE_JINJA2:
            route.routing_template = route.filtering_term
        route.save()

class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_channelfilter_filtering_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelfilter',
            name='routing_template',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
