# Generated by Django 3.2.18 on 2023-04-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_channelfilter_filtering_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreceivechannel',
            name='description_short',
            field=models.TextField(default=None, null=True),
        ),
    ]
