# Generated by Django 3.2.18 on 2023-04-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alertreceivechannel_description_short'),
        ('alerts', '0011_auto_20230329_1617'),
    ]

    operations = [
    ]
