# Generated by Django 3.2.18 on 2023-04-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_auto_20230329_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreceivechannel',
            name='description_short',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
