# Generated by Django 3.2.18 on 2023-04-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_alertreceivechannel_description_short'),
        ('alerts', '0012_auto_20230406_1010'),
    ]

    operations = [
    ]
