# Generated by Django 3.2.18 on 2023-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_alertreceivechannel_restricted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertgroup',
            name='acknowledged_by',
            field=models.IntegerField(choices=[(0, 'source'), (1, 'user'), (2, 'not yet'), (3, 'last escalation step'), (4, 'archived'), (5, 'wiped'), (6, 'stop maintenance'), (7, 'not yet, autoresolve disabled')], default=2),
        ),
        migrations.AlterField(
            model_name='alertgroup',
            name='resolved_by',
            field=models.IntegerField(choices=[(0, 'source'), (1, 'user'), (2, 'not yet'), (3, 'last escalation step'), (4, 'archived'), (5, 'wiped'), (6, 'stop maintenance'), (7, 'not yet, autoresolve disabled')], default=2),
        ),
    ]
