# Generated by Django 3.2.18 on 2023-04-28 11:48

from django.db import migrations
from django.db.models import Q


def set_field_if_web_template_is_not_default(apps, schema_editor):
    AlertReceiveChannel = apps.get_model("alerts", "AlertReceiveChannel")
    for alert_receive_channel in AlertReceiveChannel.objects.filter(
        Q(web_title_template__isnull=False)
        | Q(web_message_template__isnull=False)
        | Q(web_image_template__isnull=False)
    ).all():
        print(alert_receive_channel.web_message_template)
        print("====================================")
        print()

    AlertReceiveChannel.objects.filter(web_title_template__isnull=False).count()
    AlertReceiveChannel.objects.filter(web_message_template__isnull=False).count()


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0014_alertreceivechannel_restricted_at"),
    ]

    operations = [
        # migrations.RunPython(),
    ]
