# Generated by Django 3.2.19 on 2023-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0015_auto_20230508_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='response_time',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='restarted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
