# Generated by Django 3.2.19 on 2023-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_auto_20230523_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='is_restricted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
