# Generated by Django 3.2.19 on 2023-07-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20230411_1358'),
        ('slack', '0003_delete_slackactionrecord'),
        ('alerts', '0018_remove_alertreceivechannel_integration_slack_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationpolicy',
            name='notify_to_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies', to='slack.slackusergroup'),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='notify_to_users_queue',
            field=models.ManyToManyField(related_name='escalation_policy_notify_queues', to='user_management.User'),
        ),
    ]
