# Generated by Django 3.2.20 on 2023-07-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0019_auto_20230705_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertgroup',
            name='active_cache_for_web_calculation_id',
        ),
        migrations.RemoveField(
            model_name='alertgroup',
            name='estimate_escalation_finish_time',
        ),
        migrations.AlterField(
            model_name='alertgroup',
            name='cached_render_for_web',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
