# Generated by Django 3.2.20 on 2023-07-18 06:41

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):
    """
    See the comment in the Migration class in engine/apps/alerts/migrations/0004_auto_20220711_1106.py,
    we are commenting out this migration for essentially the same reason
    """

    dependencies = [
        ('alerts', '0021_alter_alertgroup_started_at'),
    ]

    operations = [
        linter.IgnoreMigration(),
        # migrations.AlterField(
        #     model_name='alertgroup',
        #     name='manual_severity',
        #     field=models.IntegerField(choices=[(0, 'high'), (1, 'low'), (2, 'none')], default=2, null=True),
        # ),
    ]
