# Generated by Django 3.2.20 on 2023-07-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0021_alter_alertgroup_started_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alertgroup',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='alertgroup',
            name='is_archived',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
