# Generated by Django 3.2.20 on 2023-07-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0021_alter_alertgroup_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertgroup',
            name='manual_severity',
        ),
        migrations.RemoveField(
            model_name='alertgroup',
            name='resolution_note_ts',
        ),
    ]
