# Generated by Django 3.2.20 on 2023-07-18 09:53

from django.db import migrations, models
import django_migration_linter as linter

# TODO: fix duplicates


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0022_alter_alertgroup_manual_severity'),
    ]

    operations = [
        linter.IgnoreMigration(),  # adding a unique constraint after fixing duplicates should be fine
        migrations.AlterModelOptions(
            name='escalationpolicy',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='escalationpolicy',
            constraint=models.UniqueConstraint(fields=('escalation_chain_id', 'order'), name='unique_escalation_policy_order'),
        ),
    ]
