# Generated by Django 3.2.20 on 2023-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0023_auto_20230718_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelfilter',
            options={'ordering': ['alert_receive_channel_id', 'is_default', 'order']},
        ),
        migrations.AlterField(
            model_name='channelfilter',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='channelfilter',
            constraint=models.UniqueConstraint(fields=('alert_receive_channel_id', 'is_default', 'order'), name='unique_channel_filter_order'),
        ),
    ]
