# Generated by Django 3.2.20 on 2023-07-19 10:10

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0025_auto_20230718_1042'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name='alertgroup',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='alertgroup',
            name='manual_severity',
        ),
        migrations.RemoveField(
            model_name='alertgroup',
            name='resolution_note_ts',
        ),
    ]
