# Generated by Django 3.2.20 on 2023-07-25 09:47

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0026_auto_20230719_1010'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name='alertreceivechannel',
            name='restricted_at',
        ),
    ]
