# Generated by Django 3.2.20 on 2023-07-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0027_remove_alertreceivechannel_restricted_at_from_state"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE alerts_alertreceivechannel DROP COLUMN restricted_at",
            reverse_sql=migrations.RunSQL.noop
        )
    ]
