# Generated by Django 3.2.20 on 2023-07-26 06:41

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0027_remove_alertreceivechannel_restricted_at_from_state"),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RunSQL(
            sql="ALTER TABLE alerts_alertreceivechannel DROP COLUMN restricted_at",
            reverse_sql="ALTER TABLE alerts_alertreceivechannel ADD COLUMN restricted_at datetime(6) NULL"
        )
    ]
