# Generated by Django 3.2.20 on 2023-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0030_auto_20230731_0341'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resolutionnoteslackmessage',
            index=models.Index(fields=['ts', 'thread_ts', 'alert_group_id'], name='alerts_reso_ts_08f72c_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionnoteslackmessage',
            index=models.Index(fields=['ts', 'thread_ts', 'slack_channel_id'], name='alerts_reso_ts_a9bdf7_idx'),
        ),
    ]
