# Generated by Django 3.2.20 on 2023-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('alerts', '0032_remove_alertgroup_slack_message_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreceivechannel',
            name='labels',
            field=models.ManyToManyField(through='labels.AlertReceiveChannelAssociatedLabel', to='labels.Label'),
        ),
    ]
