# Generated by Django 3.2.20 on 2023-10-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0032_remove_alertgroup_slack_message_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgrouplogrecord',
            name='action_source',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name=[(0, 'Slack'), (1, 'Web'), (2, 'Phone'), (3, 'Telegram'), (4, 'API')]),
        ),
    ]
