# Generated by Django 3.2.20 on 2023-10-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0033_alertgrouplogrecord_action_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionnote',
            name='source',
            field=models.IntegerField(choices=[(0, 'Slack'), (1, 'Web'), (2, 'Mobile App')], default=None, null=True),
        ),
    ]
