# Generated by Django 4.2.6 on 2023-10-31 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_alter_organization_maintenance_author'),
        ('alerts', '0034_alter_resolutionnote_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='grafana_incident_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alertreceivechannel',
            name='maintenance_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maintenances_created', to='user_management.user'),
        ),
    ]
