# Generated by Django 4.2.6 on 2023-10-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0035_alter_alertreceivechannel_maintenance_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='grafana_incident_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
