# Generated by Django 4.2.6 on 2023-11-02 11:39

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0036_alertgroup_grafana_incident_id'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name='alertgroup',
            name='is_restricted',
        ),
    ]
