# Generated by Django 4.2.6 on 2023-11-03 23:02

import common.migrations.remove_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0037_remove_alertgroup_is_restricted_state'),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldDB(
            model_name='AlertGroup',
            name='is_restricted',
            remove_state_migration=('alerts', '0037_remove_alertgroup_is_restricted_state'),
        ),
    ]
