# Generated by Django 4.2.7 on 2023-11-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0038_remove_alertgroup_is_restricted_db'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alertreceivechannel',
            name='unique integration name',
        ),
    ]
