# Generated by Django 3.2.20 on 2023-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0038_remove_alertgroup_is_restricted_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreceivechannel',
            name='alert_group_labels_custom',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='alertreceivechannel',
            name='alert_group_labels_template',
            field=models.TextField(default=None, null=True),
        ),
    ]
