# Generated by Django 4.2.7 on 2023-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0039_remove_alertreceivechannel_unique_integration_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='alertreceivechannel',
            constraint=models.UniqueConstraint(models.F('organization'), models.Case(models.When(team=None, then=0), default=models.F('team'), output_field=models.BigIntegerField()), models.Case(models.When(deleted_at__isnull=True, then=True), default=None), models.Case(models.When(integration='direct_paging', then=True), default=None), name='unique_direct_paging_integration_per_team'),
        ),
    ]
