# Generated by Django 4.2.7 on 2023-12-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0041_alertreceivechannel_unique_direct_paging_integration_per_team'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alertgroup',
            index=models.Index(fields=['channel_id', 'resolved', 'acknowledged', 'silenced', 'root_alert_group_id', 'started_at'], name='alert_group_list_index'),
        ),
        migrations.RemoveIndex(
            model_name='alertgroup',
            name='alerts_aler_channel_81aeec_idx',
        ),
    ]
