# Generated by Django 4.2.7 on 2023-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0041_alertreceivechannel_unique_direct_paging_integration_per_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='received_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
