# Generated by Django 3.2.19 on 2023-07-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0041_alertreceivechannel_unique_direct_paging_integration_per_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationpolicy',
            name='notify_to_team_members',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies', to='user_management.Team'),
        ),
    ]
