# Generated by Django 4.2.7 on 2024-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0044_alertreceivechannel_alertmanager_v2_backup_templates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreceivechannel',
            name='mobile_app_message_template',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alertreceivechannel',
            name='mobile_app_title_template',
            field=models.TextField(default=None, null=True),
        ),
    ]
