# Generated by Django 4.2.10 on 2024-03-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0045_escalationpolicy_notify_to_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreceivechannel',
            name='additional_settings',
            field=models.JSONField(default=None, null=True),
        ),
    ]
