# Generated by Django 4.2.10 on 2024-03-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0046_alertreceivechannelconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreceivechannel',
            name='additional_settings',
            field=models.JSONField(default=None, null=True),
        ),
    ]
