# Generated by Django 4.2.10 on 2024-03-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0047_alertreceivechannel_additional_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertGroupExternalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512)),
                ('alert_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='alerts.alertgroup')),
                ('source_alert_receive_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='alerts.alertreceivechannel')),
            ],
            options={
                'indexes': [models.Index(fields=['value'], name='alerts_aler_value_69ba4f_idx')],
                'unique_together': {('source_alert_receive_channel', 'alert_group')},
            },
        ),
    ]
