# Generated by Django 4.2.11 on 2024-04-02 13:54

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0050_alter_alertgrouplogrecord_type'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='custom_button_trigger',
        ),
    ]
