# Generated by Django 4.2.11 on 2024-04-08 20:58

import json
from django.db import migrations, models
from django.db.models import F


def migrate_old_column(apps, schema_editor):
    AlertGroup = apps.get_model("alerts", "AlertGroup")

    for obj in AlertGroup.objects.filter(grafana_incident_id__isnull=False):
        obj.grafana_incident_ids = [obj.grafana_incident_id]
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0051_remove_escalationpolicy_custom_button_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='grafana_incident_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(migrate_old_column),
    ]
