# Generated by Django 4.2.10 on 2024-05-28 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_user_google_calendar_settings'),
        ('alerts', '0051_remove_escalationpolicy_custom_button_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.BooleanField()),
                ('notification_channel', models.PositiveSmallIntegerField(default=0)),
                ('last_notified', models.DateTimeField(default=None, null=True)),
                ('notification_task_id', models.CharField(default=None, max_length=100, null=True)),
                ('notification_data', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
                ('eta', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usernotificationbundle',
            constraint=models.UniqueConstraint(fields=('user', 'important', 'notification_channel'), name='unique_user_notification_bundle'),
        ),
    ]
