# Generated by Django 4.2.11 on 2024-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0052_alter_channelfilter_filtering_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelfilter',
            name='filtering_labels',
            field=models.JSONField(default=None, null=True),
        ),
    ]
