# Generated by Django 4.2.15 on 2024-08-19 21:54

import common.migrations.remove_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0055_alter_bundlednotification_alert_group'),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldState(
            model_name='AlertGroup',
            name='slack_log_message',
        ),
    ]
