# Generated by Django 4.2.15 on 2024-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0057_remove_alertgroup_slack_log_message_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertgroup',
            name='reason_to_skip_escalation',
            field=models.IntegerField(choices=[(0, 'account_inactive'), (1, 'is_archived'), (2, 'no_reason'), (3, 'rate_limited'), (4, 'channel_not_specified'), (5, 'restricted_action'), (6, 'invalid_auth')], default=2),
        ),
    ]
