# Generated by Django 4.2.15 on 2024-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0059_alter_escalationpolicy_step_declaredincident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationpolicy',
            name='severity',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
