# Generated by Django 4.2.15 on 2024-10-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0060_relatedincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertgroup',
            name='resolved_by_alert',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolved_alert_groups', to='alerts.alert'),
        ),
    ]
