# Generated by Django 4.2.16 on 2024-11-01 10:58
import logging

from django.db import migrations
import django_migration_linter as linter

logger = logging.getLogger(__name__)

def populate_slack_channel(apps, schema_editor):
    ChannelFilter = apps.get_model("alerts", "ChannelFilter")
    SlackChannel = apps.get_model("slack", "SlackChannel")
    AlertReceiveChannel = apps.get_model("alerts", "AlertReceiveChannel")
    Organization = apps.get_model("user_management", "Organization")

    logger.info("Starting migration to populate slack_channel field.")

    # this query performs an UPDATE on the ChannelFilter table (cf), setting the slack_channel_id by
    # joining with the SlackChannel (sc), AlertReceiveChannel (arc), and Organization (org) tables
    # Since this operation is executed directly by the database, which is optimized for such set-based operations,
    # it's much faster than iterating over records in Python
    sql = f"""
    UPDATE {ChannelFilter._meta.db_table} AS cf
    JOIN {AlertReceiveChannel._meta.db_table} AS arc ON arc.id = cf.alert_receive_channel_id
    JOIN {Organization._meta.db_table} AS org ON org.id = arc.organization_id
    JOIN {SlackChannel._meta.db_table} AS sc ON sc.slack_id = cf._slack_channel_id
                                   AND sc.slack_team_identity_id = org.slack_team_identity_id
    SET cf.slack_channel_id = sc.id
    WHERE cf._slack_channel_id IS NOT NULL
      AND org.slack_team_identity_id IS NOT NULL;
    """

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql)
        updated_rows = cursor.rowcount  # Number of rows updated

    logger.info(f"Bulk updated {updated_rows} ChannelFilters with their Slack channel.")
    logger.info("Finished migration to populate slack_channel field.")


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0062_rename_slack_channel_id_channelfilter__slack_channel_id_and_more'),
    ]

    operations = [
        # simply setting this new field is okay, we are not deleting the value of channel
        # therefore, no need to revert it
        linter.IgnoreMigration(),
        migrations.RunPython(populate_slack_channel, migrations.RunPython.noop),
    ]
