# Generated by Django 4.2.16 on 2024-11-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0026_auto_20241017_1919'),
        ('alerts', '0064_migrate_resolutionnoteslackmessage_slack_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='teams',
            field=models.ManyToManyField(to='user_management.team'),
        ),
    ]
