# Generated by Django 4.2.16 on 2024-11-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0065_alertgroup_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelfilter',
            name='update_team',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
