# Generated by Django 4.2.16 on 2024-11-20 20:21

import common.migrations.remove_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0066_remove_channelfilter__slack_channel_id_and_more'),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldState(
            model_name='channelfilter',
            name='_slack_channel_id',
        ),
    ]
