# Generated by Django 4.2.16 on 2024-11-20 20:21

import common.migrations.remove_field
import django_migration_linter as linter
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0068_remove_resolutionnoteslackmessage__slack_channel_id_state'),
    ]

    operations = [
        linter.IgnoreMigration(),
        common.migrations.remove_field.RemoveFieldDB(
            model_name='channelfilter',
            name='_slack_channel_id',
            remove_state_migration=('alerts', '0067_remove_channelfilter__slack_channel_id_state'),
        ),
    ]
