# Generated by Django 4.2.16 on 2024-11-20 20:23

# import common.migrations.remove_field
# import django_migration_linter as linter
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0069_remove_channelfilter__slack_channel_id_db'),
    ]

    operations = [
        # NOTE: commented out due to some issues this was causing w/ SQLite:
        # https://github.com/grafana/oncall/issues/5306
        # https://github.com/grafana/oncall/issues/5244#issuecomment-2503999986
        #
        # linter.IgnoreMigration(),
        # common.migrations.remove_field.RemoveFieldDB(
        #     model_name='resolutionnoteslackmessage',
        #     name='_slack_channel_id',
        #     remove_state_migration=('alerts', '0068_remove_resolutionnoteslackmessage__slack_channel_id_state'),
        # ),
    ]
