# Generated by Django 4.2.11 on 2024-12-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0007_customfield_integrationhascustomfield'),
        ('alerts', '0071_migrate_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertreceivechannel',
            name='custom_fields',
            field=models.ManyToManyField(through='labels.IntegrationHasCustomField', to='labels.customfield'),
        ),
    ]
