# Generated by Django 4.2.11 on 2024-12-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0071_migrate_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertgroup',
            name='custom_fields',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaname', models.CharField(max_length=200)),
                ('spec', models.JSONField()),
                ('template', models.TextField(default=None, null=True)),
                ('static_value', models.CharField(default=None, max_length=200, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='alerts.alertreceivechannel')),
            ],
            options={
                'unique_together': {('integration', 'metaname')},
            },
        ),
    ]
