# Generated by Django 4.2.16 on 2024-12-04 11:47

import common.migrations.remove_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0071_migrate_labels'),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldState(
            model_name='AlertGroup',
            name='prevent_posting_alerts',
        ),
    ]
