# Generated by Django 4.2.15 on 2024-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0074_alter_escalationpolicy_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertgrouplogrecord',
            name='action_source',
            field=models.SmallIntegerField(default=None, null=True, verbose_name=[(0, 'Slack'), (1, 'Web'), (2, 'Phone'), (3, 'Telegram'), (4, 'API'), (5, 'Backsync'), (6, 'Mattermost')]),
        ),
    ]
