# Generated by Django 3.2.5 on 2021-08-04 10:46

import sys
from django.db import migrations
from apps.public_api import constants as public_api_constants
from common.constants.role import Role


def create_demo_token_instances(apps, schema_editor):
    if not (len(sys.argv) > 1 and sys.argv[1] == 'test'):
        SlackUserIdentity = apps.get_model('slack', 'SlackUserIdentity')
        SlackTeamIdentity = apps.get_model('slack', 'SlackTeamIdentity')
        User = apps.get_model('user_management', 'User')
        Organization = apps.get_model('user_management', 'Organization')

        slack_team_identity = SlackTeamIdentity.objects.get(slack_id=public_api_constants.DEMO_SLACK_TEAM_ID)
        slack_user_identity = SlackUserIdentity.objects.get(
            slack_id=public_api_constants.DEMO_SLACK_USER_ID,
            slack_team_identity=slack_team_identity,
        )

        organization, _ = Organization.objects.get_or_create(
            public_primary_key=public_api_constants.DEMO_ORGANIZATION_ID,
            defaults=dict(
                slack_team_identity=slack_team_identity,
                org_id=0, stack_id=0,
            )
        )
        User.objects.get_or_create(
            public_primary_key=public_api_constants.DEMO_USER_ID,
            defaults=dict(
                username=public_api_constants.DEMO_USER_USERNAME,
                email=public_api_constants.DEMO_USER_EMAIL,
                organization=organization,
                role=Role.ADMIN,
                slack_user_identity=slack_user_identity,
                user_id=0,
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_squashed_initial'),
        ('slack', '0003_squashed_create_demo_token_instances'),
    ]

    operations = [
        migrations.RunPython(create_demo_token_instances, migrations.RunPython.noop)
    ]
