# Generated by Django 3.2.5 on 2022-08-25 08:51

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20220705_1214'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name='user',
            name='hide_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
