# Generated by Django 3.2.15 on 2022-10-25 03:16

from django.db import migrations, models
import django.db.models.deletion
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_hide_phone_number'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('oncall_backend_url', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='region_slug',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='migration_destination',
            field=models.ForeignKey(db_column='migration_destination_slug', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='user_management.region', to_field='slug'),
        ),
    ]
