# Generated by Django 3.2.15 on 2022-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_hide_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='region_slug',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
