# Generated by Django 3.2.15 on 2022-10-25 11:18

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20221025_0316'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name='organization',
            name='is_rbac_permissions_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(default=list),
        ),
    ]
