# Generated by Django 3.2.15 on 2022-10-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20221020_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
