# Generated by Django 3.2.16 on 2023-01-16 09:41

from django.db import migrations, models
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_organization_deleted_at'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name='organization',
            name='is_grafana_incident_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
