# Generated by Django 3.2.16 on 2023-02-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_organization_is_grafana_incident_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asterisk_otp',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
