# Generated by Django 3.2.18 on 2023-03-15 06:21

from django.db import migrations, models
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_organization_cluster_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_sharing_resources_to_all',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField enforces the default value on the app level, which leads to the issues during release
        # adding same default value on the database level
        AddDefaultValue(
            model_name='team',
            name='is_sharing_resources_to_all',
            value=False
        )
    ]
