# Generated by Django 3.2.18 on 2023-03-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_team_is_sharing_resources_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='gcom_org_contract_type',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='gcom_org_has_irm_sku',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='gcom_org_oldest_admin_with_billing_privileges_user_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
