# Generated by Django 3.2.20 on 2023-07-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20230411_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='archive_alerts_from',
            field=models.DateField(default='1970-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_amixr_migration_started',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
