# Generated by Django 3.2.20 on 2023-07-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20230411_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='archive_alerts_from',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_amixr_migration_started',
        ),
    ]
