# Generated by Django 3.2.20 on 2023-07-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_auto_20230711_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='acknowledge_remind_timeout',
            field=models.IntegerField(choices=[(0, 'Never remind'), (1, 'Remind every 1 hour'), (2, 'Remind every 3 hours'), (3, 'Remind every 5 hours'), (4, 'Remind every 10 hours')], default=0),
        ),
    ]
