# Generated by Django 3.2.20 on 2023-07-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0029_auto_20230728_0802'),
        ('user_management', '0013_alter_organization_acknowledge_remind_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_team_users', to='user_management.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification',
            field=models.ManyToManyField(related_name='users', through='alerts.UserHasNotification', to='alerts.AlertGroup'),
        ),
    ]
