# Generated by Django 3.2.20 on 2023-09-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_auto_20230728_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_notification_channel',
            field=models.IntegerField(choices=[(0, 'Slack'), (1, 'Sms'), (2, 'Phone Call'), (3, 'Telegram'), (5, 'Mobile App'), (6, 'Mobile App Critical'), (8, 'Email')], default=8, null=True),
        ),
    ]
