# Generated by Django 3.2.20 on 2023-09-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_auto_20230926_2203'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'is_active', 'username', 'role'], name='user_manage_organiz_88c7db_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'is_active', 'email', 'role'], name='user_manage_organiz_696988_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'organization', 'is_active', 'permissions'], name='user_manage_usernam_66f94c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'organization', 'is_active', 'permissions'], name='user_manage_email_c4f4fb_idx'),
        ),
    ]
