# Generated by Django 4.2.6 on 2023-10-31 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='maintenance_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_maintenances_created', to='user_management.user'),
        ),
    ]
