# Generated by Django 4.2.7 on 2023-11-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_alter_organization_maintenance_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='grafana_incident_backend_url',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
