# Generated by Django 3.2.20 on 2023-11-15 12:06

import apps.api.alert_group_table_columns
from django.db import migrations, models

import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_alter_organization_maintenance_author'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.AddField(
            model_name='organization',
            name='alert_group_table_columns',
            field=models.JSONField(default=apps.api.alert_group_table_columns.default_columns),
        ),
        migrations.AddField(
            model_name='user',
            name='alert_groups_table_selected_columns',
            field=models.JSONField(default=None, null=True),
        ),
    ]
