# Generated by Django 4.2.7 on 2024-01-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_organization_grafana_incident_backend_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_grafana_labels_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
