# Generated by Django 4.2.10 on 2024-02-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_organization_is_grafana_labels_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_slack_alert_group_log_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
