# Generated by Django 4.2.10 on 2024-03-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_organization_is_grafana_labels_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_calendar_settings',
            field=models.JSONField(default=None, null=True),
        ),
    ]
