# Generated by Django 4.2.15 on 2024-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_alter_team_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_grafana_irm_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
