# Generated by Django 4.2.15 on 2024-10-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_organization_is_grafana_irm_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grafana_id', models.PositiveIntegerField(null=True)),
                ('login', models.CharField(max_length=300)),
                ('last_synced_at', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='user_management.organization')),
            ],
            options={
                'unique_together': {('grafana_id', 'organization')},
            },
        ),
    ]
