# Generated by Django 4.2.16 on 2024-10-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_slackteamidentity__unified_slack_app_installed'),
        ('user_management', '0024_organization_direct_paging_prefer_important_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_slack_channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='slack.slackchannel'),
        ),
    ]
