# Generated by Django 4.2.15 on 2024-10-17 19:19
import logging

from django.db import migrations
import django_migration_linter as linter

logger = logging.getLogger(__name__)


def populate_general_log_slack_channel(apps, schema_editor):
    Organization = apps.get_model('user_management', 'Organization')
    SlackChannel = apps.get_model('slack', 'SlackChannel')

    logger.info("Starting migration to populate general_log_slack_channel field.")

    queryset = Organization.objects.filter(general_log_channel_id__isnull=False, slack_team_identity__isnull=False)
    total_orgs = queryset.count()
    updated_orgs = 0
    missing_channels = 0

    logger.info(f"Total organizations to process: {total_orgs}")

    for org in queryset:
        slack_id = org.general_log_channel_id
        slack_team_identity = org.slack_team_identity

        try:
            slack_channel = SlackChannel.objects.get(slack_id=slack_id, slack_team_identity=slack_team_identity)

            org.general_log_slack_channel = slack_channel
            org.save(update_fields=['general_log_slack_channel'])

            updated_orgs += 1
            logger.info(
                f"Organization {org.id} updated with SlackChannel {slack_channel.id} (slack_id: {slack_id})."
            )
        except SlackChannel.DoesNotExist:
            missing_channels += 1
            logger.warning(
                f"SlackChannel with slack_id '{slack_id}' and slack_team_identity '{slack_team_identity}' "
                f"does not exist for Organization {org.id}."
            )

    logger.info(
        f"Finished migration. Total organizations processed: {total_orgs}. "
        f"Organizations updated: {updated_orgs}. Missing SlackChannels: {missing_channels}."
    )

class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_organization_general_log_slack_channel'),
    ]

    operations = [
        # simply setting this new field is okay, we are not deleting the value of general_log_channel_id
        # therefore, no need to revert it
        linter.IgnoreMigration(),
        migrations.RunPython(populate_general_log_slack_channel, migrations.RunPython.noop),
    ]
