# Generated by Django 4.2.15 on 2024-10-17 19:19
import logging

from django.db import migrations
import django_migration_linter as linter

logger = logging.getLogger(__name__)


def populate_default_slack_channel(apps, schema_editor):
    Organization = apps.get_model("user_management", "Organization")
    SlackChannel = apps.get_model("slack", "SlackChannel")

    logger.info("Starting migration to populate default_slack_channel field.")

    sql = f"""
    UPDATE {Organization._meta.db_table} AS org
    JOIN {SlackChannel._meta.db_table} AS sc ON sc.slack_id = org.general_log_channel_id
                         AND sc.slack_team_identity_id = org.slack_team_identity_id
    SET org.default_slack_channel_id = sc.id
    WHERE org.general_log_channel_id IS NOT NULL
      AND org.slack_team_identity_id IS NOT NULL;
    """

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(sql)
        updated_rows = cursor.rowcount  # Number of rows updated

    logger.info(f"Bulk updated {updated_rows} organizations with their default Slack channel.")
    logger.info("Finished migration to populate default_slack_channel field.")

class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0025_organization_default_slack_channel"),
    ]

    operations = [
        # simply setting this new field is okay, we are not deleting the value of general_log_channel_id
        # therefore, no need to revert it
        linter.IgnoreMigration(),
        migrations.RunPython(populate_default_slack_channel, migrations.RunPython.noop),
    ]
