# Generated by Django 4.2.16 on 2024-11-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0026_auto_20241017_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='general_log_channel_id',
        ),
    ]
