# Generated by Django 4.2.16 on 2024-11-06 21:11

from django.db import migrations
import django_migration_linter as linter


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0026_auto_20241017_1919'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RemoveField(
            model_name='organization',
            name='general_log_channel_id',
        ),
    ]
