# Generated by Django 4.2.16 on 2024-11-20 17:58

import common.migrations.remove_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0027_serviceaccount'),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldState(
            model_name='organization',
            name='general_log_channel_id',
        ),
    ]
