# Generated by Django 4.2.16 on 2024-11-20 17:58

import common.migrations.remove_field
import django_migration_linter as linter
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0028_remove_organization_general_log_channel_id_state'),
    ]

    operations = [
        linter.IgnoreMigration(),
        common.migrations.remove_field.RemoveFieldDB(
            model_name='organization',
            name='general_log_channel_id',
            remove_state_migration=('user_management', '0028_remove_organization_general_log_channel_id_state'),
        ),
    ]
