# Generated by Django 4.2.16 on 2024-11-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0028_remove_organization_general_log_channel_id_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blahblah',
            name='foo_bar',
        ),
    ]
