# Generated by Django 3.2.18 on 2023-04-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncallphonecall',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='oncallphonecall',
            name='status',
        ),
        migrations.RemoveField(
            model_name='oncallsms',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='oncallsms',
            name='status',
        ),
    ]
