# Generated by Django 4.2.10 on 2024-07-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_notifications', '0002_bannedphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsrecord',
            name='represents_bundle_uuid',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
    ]
