name: backend-ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Backend Checks
    runs-on: ubuntu-latest
    container: python:3.9
    env:
      DJANGO_SETTINGS_MODULE: settings.ci-test
      SLACK_CLIENT_OAUTH_ID: 1
    services:
      rabbit_test:
        image: rabbitmq:3.7.19
        env:
          RABBITMQ_DEFAULT_USER: rabbitmq
          RABBITMQ_DEFAULT_PASS: rabbitmq

    steps:
      - uses: actions/checkout@v2
      - name: Lint Backend
        run: |
          pip install $(grep "pre-commit" engine/requirements.txt)
          pre-commit run isort --all-files
          pre-commit run black --all-files
          pre-commit run flake8 --all-files

      - name: Test Backend
        run: |
          apt-get update && apt-get install -y netcat
          cd engine/
          mkdir sqlite_data
          pip install -r requirements.txt
          pytest --ds=settings.ci-test