name: Add issues to projects

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add OSS issues to team's kanban board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/grafana/projects/119
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}