name: e2e Tests

# tldr; allows running e2e tests, which access repository secrets
#
# From a GitHub security blog post
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
# Together with the pull_request_target, a new trigger workflow_run was introduced to enable scenarios
# that require building the untrusted code and also need write permissions to update the PR with e.g.
# code coverage results or other test results. To do this in a secure manner, the untrusted code must be
# handled via the pull_request trigger so that it is isolated in an unprivileged environment. The workflow
# processing the PR should then store any results like code coverage or failed/passed tests in artifacts and
# exit. The following workflow then starts on workflow_run where it is granted write permission to the target
# repository and access to repository secrets, so that it can download the artifacts and make any necessary
# modifications to the repository or interact with third party services that require repository secrets
# (e.g. API tokens).
#
# More references
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
on:
  workflow_run:
    workflows:
      - Linting and Unit Tests
    types:
      - completed

jobs:
  end-to-end-tests:
    name: End to end tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/e2e-tests.yml
    with:
      # TODO: fix issues with running e2e tests against Grafana v10.2.x and v10.3.x
      grafana-image-tag: 10.1.7
      # grafana-image-tag: 10.3.3
      run-expensive-tests: false
      browsers: "chromium"
    secrets: inherit
