name: publish-technical-documentation-release

on:
  push:
    branches:
      - "release-*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths:
      - "docs/sources/**"
  workflow_dispatch:
jobs:
  sync:
    if: github.repository == 'grafana/oncall'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # publish-technical-documentation-release/v2.2.4
      - uses: grafana/writers-toolkit/publish-technical-documentation-release@8cc658b604c6e05c275af30163a1c7728dfe19b2
        with:
          release_tag_regexp: "^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
          release_branch_regexp: "^release-(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
          release_branch_with_patch_regexp: "^release-(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$"
          website_directory: content/docs/oncall
