name: snyk

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.0
      - uses: snyk/actions/setup@master
      - name: Install Dependencies
        run: |
          pip install -r engine/requirements.txt
          cd grafana-plugin/
          yarn --network-timeout 500000
      - name: Run Snyk
        continue-on-error: true
        run: snyk test --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}