# NOTE: this is being left in this directory on purpose, it will be moved to apps/alerts/migrations
# in a separate PR/release
#
# Generated by Django 4.2.16 on 2024-12-04 11:47

from django.db import migrations

import common.migrations.remove_field


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0072_remove_alertgroup_prevent_posting_alerts_state"),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldDB(
            model_name="AlertGroup",
            name="prevent_posting_alerts",
            remove_state_migration=("alerts", "0072_remove_alertgroup_prevent_posting_alerts_state"),
        ),
    ]
