# Generated by Django 4.2.15 on 2024-08-19 21:54

from django.db import migrations

import common.migrations.remove_field


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0056_remove_alertgroup_slack_log_message_state'),
    ]

    operations = [
        common.migrations.remove_field.RemoveFieldDB(
            model_name='AlertGroup',
            name='slack_log_message',
            remove_state_migration=('alerts', '0056_remove_alertgroup_slack_log_message_state'),
        ),
    ]
